import{beforeEach,describe,expect,it}from'vitest';
import{atomicReplace,db,defaults,getSettings}from'../db';
import{applySuggestedMappings,builtInDefaultSchedule,resolveSchedule}from'../schedule';
import{localAppServices}from'../services';
import{createEncryptedBackup,finishActive,restoreAnyBackup}from'../lib';
import{generateLookupSecret}from'../privacy';
import type{BellSchedule,ClassRecord,QueueEntry,Student}from'../types';

const at=(day:number,hour:number,minute:number)=>new Date(2026,7,2+day,hour,minute);
const mapped=()=>{const schedule=builtInDefaultSchedule(at(1,8,0));for(const blocks of Object.values(schedule.days))for(const block of blocks)if(block.periodKey)block.classId=`class-${block.periodKey}`;return schedule};
const state=(day:number,time:string,schedule:BellSchedule=mapped())=>{const[h,m]=time.split(':').map(Number);return resolveSchedule(schedule,at(day,h,m))};

describe('built-in bell schedule',()=>{
 it.each([[1,'08:44','non-class'],[1,'08:45','P1'],[1,'10:15','passing'],[1,'10:25','P3'],[1,'12:00','lunch'],[1,'12:36','passing'],[1,'12:40','P5'],[1,'14:20','P7'],[1,'15:50','non-class'],[2,'08:45','P2'],[2,'10:25','P4'],[2,'12:40','PCBL'],[2,'13:35','P6'],[3,'08:45','P1'],[3,'09:35','passing'],[3,'09:40','P2'],[3,'10:30','break'],[3,'10:40','P3'],[3,'11:35','P4'],[3,'12:30','lunch'],[3,'13:10','P5'],[3,'14:05','P6'],[3,'14:55','passing'],[3,'15:05','P7'],[3,'15:55','non-class'],[4,'10:25','P3'],[5,'13:35','P6']] as const)('resolves day %s at %s as %s',(day,time,expected)=>{const result=state(day,time);expect(result.block?.periodKey??result.kind).toBe(expected)});
 it('suggests only recognizable P1-P7 mappings',()=>{const t=new Date().toISOString(),classes=[{id:'p3',period:'P3',createdAt:t,updatedAt:t},{id:'p6',calendar:'P6',createdAt:t,updatedAt:t},{id:'unclear',period:'Advisory',createdAt:t,updatedAt:t}];const result=applySuggestedMappings(builtInDefaultSchedule(),classes);expect(result.days[1].find(x=>x.periodKey==='P3')?.classId).toBe('p3');expect(result.days[2].find(x=>x.periodKey==='P6')?.classId).toBe('p6');expect(JSON.stringify(result)).not.toContain('unclear')});
 it('keeps the bathroom line open when no class is active',()=>{expect(state(1,'08:44').lineOpen).toBe(true);expect(state(1,'10:15').lineOpen).toBe(true);expect(state(1,'12:00').lineOpen).toBe(true)});
});

const stamp='2026-08-03T15:00:00.000Z';
const student=(id:string):Student=>({id,name:`Student ${id}`,externalIdHash:id.padStart(64,'0'),externalIdLast4:id.padStart(4,'0'),createdAt:stamp,updatedAt:stamp});
const classRecord=(id:string,period:string):ClassRecord=>({id,period,courseTitle:`Course ${period}`,createdAt:stamp,updatedAt:stamp});
const entry=(id:string,studentId:string,classId:string,status:'waiting'|'active',startedAt?:string):QueueEntry=>({id,studentId,classId,status,queuedAt:stamp,startedAt,createdAt:stamp,updatedAt:stamp});

describe('schedule transitions and queue history',()=>{
 beforeEach(async()=>{await db.delete();await db.open();await atomicReplace({students:[student('1'),student('2'),student('3')],classes:[classRecord('class-P1','P1'),classRecord('class-P3','P3')],enrollments:[],queue:[],queueHistory:[],sessions:[],bellSchedules:[mapped()],settings:{...defaults,setupComplete:true,lookupSecret:generateLookupSecret(),currentClassId:'class-P1',lastScheduleStateId:'2026-08-03:mon-p1|2026-08-03T16:00:00.000Z'}})});
 it('clears waiting students at class end, records period-ended, and preserves the active timer',async()=>{await db.queue.bulkAdd([entry('active','1','class-P1','active','2026-08-03T16:00:00.000Z'),entry('wait-1','2','class-P1','waiting'),entry('wait-2','3','class-P1','waiting')]);await localAppServices.reconcileSchedule(at(1,10,16));const queue=await db.queue.toArray(),history=await db.queueHistory.toArray();expect(queue).toHaveLength(1);expect(queue[0]).toMatchObject({id:'active',status:'active',startedAt:'2026-08-03T16:00:00.000Z'});expect(history.map(x=>x.exitReason)).toEqual(['period-ended','period-ended']);expect(await db.sessions.count()).toBe(0)});
 it('activates the incoming class while an outgoing active student remains',async()=>{await db.queue.add(entry('active','1','class-P1','active','2026-08-03T16:00:00.000Z'));const result=await localAppServices.reconcileSchedule(at(1,10,26));expect(result.classId).toBe('class-P3');expect((await db.queue.get('active'))?.classId).toBe('class-P1');await db.queue.add(entry('incoming','2','class-P3','waiting'));await expect(import('../lib').then(x=>x.startTimer('incoming'))).rejects.toThrow('Only the first student');const session=await finishActive();expect(session.classId).toBe('class-P1');expect((await db.queue.get('incoming'))?.status).toBe('waiting')});
 it('manual switching clears waiting students but not an active student',async()=>{await db.queue.bulkAdd([entry('active','1','class-P1','active','2026-08-03T16:00:00.000Z'),entry('waiting','2','class-P1','waiting')]);await localAppServices.manualSwitch('class-P3',false,at(1,9,0));expect((await db.queue.toArray()).map(x=>x.id)).toEqual(['active']);expect((await db.queueHistory.toArray())[0].exitReason).toBe('manual-class-switch');expect((await db.settings.get('settings'))?.currentClassId).toBe('class-P3')});
 it('pause-for-today expires on the next date',async()=>{await localAppServices.manualSwitch('class-P3',true,at(1,9,0));expect((await localAppServices.scheduleState(at(1,9,1))).classId).toBe('class-P3');await localAppServices.reconcileSchedule(at(2,9,0));expect((await db.settings.get('settings'))?.autoSchedulePausedDate).toBeUndefined()});
 it('quick clear is undoable with exact order and timestamps',async()=>{const first=entry('first','2','class-P1','waiting'),second={...entry('second','3','class-P1','waiting'),queuedAt:'2026-08-03T15:01:00.000Z'};await db.queue.bulkAdd([first,second]);const removed=await localAppServices.quickClear();expect(await db.queue.count()).toBe(0);expect((await db.queueHistory.toArray()).every(x=>x.exitReason==='teacher-quick-clear')).toBe(true);await localAppServices.undoQuickClear(removed);expect((await db.queue.toArray()).sort((a,b)=>a.queuedAt.localeCompare(b.queuedAt))).toEqual([first,second]);expect(await db.queueHistory.count()).toBe(0)});
 it('backs up and restores customized schedules and queue history',async()=>{const schedule=(await db.bellSchedules.toArray())[0];schedule.days[1][0].start='08:40';await db.bellSchedules.put(schedule);await db.queue.add(entry('waiting','2','class-P1','waiting'));await localAppServices.quickClear();const backup=await createEncryptedBackup('correct horse battery');await atomicReplace({students:[],queue:[],sessions:[],settings:{...defaults,lookupSecret:generateLookupSecret()}});await restoreAnyBackup(backup,await getSettings(),'correct horse battery');expect((await db.bellSchedules.toArray())[0].days[1][0].start).toBe('08:40');expect((await db.queueHistory.toArray())[0].exitReason).toBe('teacher-quick-clear')});
 it('allows every rostered student to join regardless of the detected class or period',async()=>{await db.enrollments.add({id:'enrollment',studentId:'1',classId:'class-P1',createdAt:stamp,updatedAt:stamp});await db.settings.put({...defaults,setupComplete:true,currentClassId:'class-P3'});const{addToQueue}=await import('../lib');const queued=await addToQueue('1');expect(queued.studentId).toBe('1');expect(queued.classId).toBe('class-P3');await db.queue.clear();await db.settings.put({...defaults,setupComplete:true,currentClassId:undefined});await expect(addToQueue('2')).resolves.toMatchObject({studentId:'2',classId:undefined})});
});
