import{test,expect,type Page}from'@playwright/test';
const aeriesFixture=`Fictional High School,Attendance Class Roster
Period,Course Title,Term,Sec#,Crs ID,Teacher,Calendar,Room,Year
P3,Government,Y,75,302745,"TEACHER, SAMPLE",P3,L207,26-27
Student ID,Student Name,GR,8/7/2026
01,170000,,"Almond, Thomas L",10,,,,
Fictional High School,Attendance Class Roster
Period,Course Title,Term,Sec#,Crs ID,Teacher,Calendar,Room,Year
P6,Civics,Y,91,302700,"TEACHER, SAMPLE",P6,L208,26-27
Student ID,Student Name,GR,8/7/2026
01,170001,,"Nets, Utah B",12,,,,`;

async function setup(page:Page){
 await page.goto('/');
 await page.getByLabel('Teacher PIN',{exact:true}).fill('2468');
 await page.getByLabel('Confirm PIN').fill('2468');
 await page.getByRole('button',{name:'Continue',exact:true}).click();
 await page.getByRole('button',{name:'Add Student Manually'}).click();
 for(const [index,[name,id]]of[['Jordan Lee','001482'],['Alex Rivera','001937']].entries()){await page.getByLabel('Full name').fill(name);await page.getByLabel('Student ID').fill(id);await page.getByRole('button',{name:'Add Student',exact:true}).click();await expect(page.getByText(`${index+1} student${index?'s':''} currently added`)).toBeVisible()}
 await page.getByRole('button',{name:'Continue to App'}).click();
 await expect(page.getByText('Ready for class')).toBeVisible();
}
async function openTeacher(page:Page){await page.keyboard.press('Control+Shift+5');await expect(page.getByRole('dialog')).toBeVisible();await page.getByLabel('Teacher PIN').fill('2468');await page.getByRole('button',{name:'Continue'}).click();await expect(page.getByText('Teacher dashboard')).toBeVisible()}
async function keypad(page:Page,id:string){await page.getByRole('button',{name:'Add/remove my name from the bathroom line'}).click();for(const digit of id)await page.locator('.keypad').getByRole('button',{name:digit,exact:true}).click()}
async function changeActiveStart(page:Page,secondsAgo:number){await page.evaluate(async seconds=>{const request=indexedDB.open('ClassroomBathroomQueue');const database=await new Promise<IDBDatabase>((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});await new Promise<void>((resolve,reject)=>{const tx=database.transaction('queue','readwrite'),store=tx.objectStore('queue'),all=store.getAll();all.onsuccess=()=>{const active=all.result.find((x:any)=>x.status==='active');active.startedAt=new Date(Date.now()-seconds*1000).toISOString();store.put(active)};tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});database.close()},secondsAgo)}

test('first-time setup requires a PIN but allows an empty roster',async({page})=>{
 await page.goto('/');
 await page.getByRole('button',{name:'Continue',exact:true}).click();await expect(page.getByRole('alert')).toContainText('at least four digits');
 await page.getByLabel('Teacher PIN',{exact:true}).fill('2468');await page.getByLabel('Confirm PIN').fill('2468');await page.getByRole('button',{name:'Continue',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Set up your roster'})).toBeVisible();await expect(page.getByRole('button',{name:'Import Aeries Class Roster'})).toBeVisible();await expect(page.getByRole('button',{name:'Import Standard Roster'})).toBeVisible();await expect(page.getByRole('button',{name:'Add Student Manually'})).toBeVisible();await expect(page.getByRole('button',{name:'Restore Full Backup'})).toBeVisible();
 await page.getByRole('button',{name:'Continue Without Students'}).click();await expect(page.getByText('Ready for class')).toBeVisible();await page.getByRole('button',{name:'Start Bathroom Kiosk'}).click();await expect(page.getByText('No students have been added yet.')).toBeVisible();await expect(page.getByText('Use teacher settings to import or add a roster.')).toBeVisible();
});

test('new teacher can import Aeries during setup without a temporary student',async({page})=>{
 await page.goto('/');await page.getByLabel('Teacher PIN',{exact:true}).fill('2468');await page.getByLabel('Confirm PIN').fill('2468');await page.getByRole('button',{name:'Continue',exact:true}).click();
 await page.locator('input[type=file][accept*="text/plain"]').setInputFiles({name:'aeries-roster.txt',mimeType:'text/plain',buffer:Buffer.from(aeriesFixture)});await page.getByRole('button',{name:'Import selected students'}).click();await expect(page.getByText('2 selected Aeries records processed.')).toBeVisible();await page.getByRole('button',{name:'Continue to App'}).click();await expect(page.getByText('Ready for class')).toBeVisible();
});

test('student kiosk flow, number pad, queue rules, thresholds, refresh, history, and removal',async({page})=>{
 await page.addInitScript(()=>{let fullscreen=false;Object.defineProperty(document,'fullscreenElement',{configurable:true,get:()=>fullscreen?document.documentElement:null});Element.prototype.requestFullscreen=async()=>{fullscreen=true;document.dispatchEvent(new Event('fullscreenchange'))};document.exitFullscreen=async()=>{fullscreen=false;document.dispatchEvent(new Event('fullscreenchange'))}});
 await setup(page);
 await page.getByRole('button',{name:'Start Bathroom Kiosk'}).click();await expect(page.getByText('The bathroom line is currently empty.')).toBeVisible();await expect(page.getByRole('button',{name:'Add/remove my name from the bathroom line'})).toHaveCSS('background-color','rgb(180, 35, 44)');
 await page.evaluate(()=>document.exitFullscreen());await expect(page.getByText('Bathroom kiosk is paused.')).toBeVisible();await expect(page.getByText('The bathroom line is currently empty.')).not.toBeVisible();await page.getByRole('button',{name:'Return to fullscreen'}).click();
 await keypad(page,'001482');await expect(page.getByRole('button',{name:/Jordan Lee/})).toContainText('••1482');await page.getByRole('button',{name:/Jordan Lee/}).click();await page.getByRole('button',{name:'Add my name for the bathroom'}).click();await expect(page.getByRole('heading',{name:'Jordan Lee'})).toBeVisible();
 await keypad(page,'001937');await page.getByRole('button',{name:/Alex Rivera/}).click();await page.getByRole('button',{name:'Add my name for the bathroom'}).click();await expect(page.locator('.queue li').nth(0)).toContainText('Jordan Lee');await expect(page.locator('.queue li').nth(1)).toContainText('Alex Rivera');
 await page.getByRole('button',{name:"I'm ready to use the bathroom"}).click();await expect(page.getByText('Your bathroom timer has started.')).toBeVisible();await expect(page.getByRole('button',{name:"I'm back"})).toHaveCSS('background-color','rgb(23, 105, 170)');
 await changeActiveStart(page,301);await page.reload();await page.getByRole('button',{name:'Start Bathroom Kiosk'}).click();await expect(page.getByText('5-minute warning')).toBeVisible();await expect(page.locator('.timer')).toHaveClass(/warning/);
 await changeActiveStart(page,421);await page.reload();await page.getByRole('button',{name:'Start Bathroom Kiosk'}).click();await expect(page.getByText('Over time limit')).toBeVisible();await expect(page.locator('.timer')).toHaveClass(/over/);
 await page.getByRole('button',{name:"I'm back"}).click();await expect(page.getByText('Welcome back.')).toBeVisible();await expect(page.getByRole('heading',{name:'Alex Rivera'})).toBeVisible();await expect(page.getByText('Waiting to start')).toBeVisible();expect(await page.evaluate(()=>Boolean(document.fullscreenElement))).toBe(true);
 await keypad(page,'001937');await page.getByRole('button',{name:/Alex Rivera/}).click();page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Remove my name from the bathroom line'}).click();await expect(page.getByText('The bathroom line is currently empty.')).toBeVisible();
 await openTeacher(page);await page.getByRole('button',{name:'Stats'}).click();const jordanStats=page.locator('.tr').filter({hasText:'Jordan Lee'}),headings=page.locator('.tr.head');await expect(jordanStats).toContainText('1');await expect(headings).toContainText('Completed uses');await expect(headings).toContainText('Over-limit uses');await expect(headings).toContainText('Over %');await expect(headings).not.toContainText('Warning / over');await expect(headings).not.toContainText('Uses / canceled');
});

test('teacher access, permanent roster storage, exports, backup restore, and offline shell',async({page,context},testInfo)=>{
 await setup(page);await page.reload();await expect(page.getByText('Ready for class')).toBeVisible();
 await page.keyboard.press('Control+Shift+5');await page.getByLabel('Teacher PIN').fill('1111');await page.getByRole('button',{name:'Continue'}).click();await expect(page.getByText('Incorrect PIN.')).toBeVisible();await page.getByLabel('Teacher PIN').fill('2468');await page.getByRole('button',{name:'Continue'}).click();
 await page.getByRole('button',{name:'Roster'}).click();await expect(page.getByText('Jordan Lee')).toBeVisible();
 await page.getByRole('button',{name:'Settings'}).click();page.once('dialog',d=>d.accept());const backupDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Export full backup'}).click();const backup=await backupDownload;const backupPath=testInfo.outputPath('backup.json');await backup.saveAs(backupPath);const backupJson=JSON.parse(await (await import('node:fs/promises')).readFile(backupPath,'utf8'));expect(backupJson.students).toHaveLength(2);expect(JSON.stringify(backupJson)).not.toContain('2468');
 await expect(page.getByRole('button',{name:'Export Roster CSV'})).not.toBeVisible();await page.getByText('Advanced Data Tools').click();const rosterDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Export Roster CSV'}).click();const roster=await rosterDownload;const rosterPath=testInfo.outputPath('roster.csv');await roster.saveAs(rosterPath);expect(await (await import('node:fs/promises')).readFile(rosterPath,'utf8')).toContain('"Jordan Lee","001482"');
 const historyDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Export bathroom history CSV'}).click();const history=await historyDownload;const historyPath=testInfo.outputPath('history.csv');await history.saveAs(historyPath);expect(await (await import('node:fs/promises')).readFile(historyPath,'utf8')).toMatch(/^studentName,studentId/);
 await page.getByRole('button',{name:'Roster',exact:true}).click();page.once('dialog',d=>d.accept());await page.locator('.adminrow').filter({hasText:'Jordan Lee'}).getByRole('button',{name:'Delete'}).click();await expect(page.getByText('Jordan Lee')).not.toBeVisible();
 await page.getByRole('button',{name:'Settings'}).click();await page.locator('input[type=file][accept*="json"]').setInputFiles(backupPath);await expect(page.getByRole('dialog')).toContainText('Restore Full Backup?');await page.getByLabel('Restore teacher PIN').fill('1111');await page.getByRole('button',{name:'Restore and Replace Current Data'}).click();await expect(page.getByText('Incorrect PIN.')).toBeVisible();await page.getByLabel('Restore teacher PIN').fill('2468');await page.getByRole('button',{name:'Restore and Replace Current Data'}).click();await expect(page.getByText('Backup restored successfully.')).toBeVisible();await page.getByRole('button',{name:'Roster',exact:true}).click();await expect(page.getByText('Jordan Lee')).toBeVisible();
 await page.evaluate(async()=>{await navigator.serviceWorker.ready});await context.setOffline(true);await page.reload();await expect(page.getByText('Classroom Bathroom Queue')).toBeVisible();await expect(page.getByText('Teacher welcome')).toBeVisible();await context.setOffline(false);
});

test('Aeries TXT preview covers all classes, cancel is safe, and selected students import',async({page})=>{await setup(page);await openTeacher(page);await page.getByRole('button',{name:'Roster',exact:true}).click();const input=page.locator('input[type=file][accept*="text/plain"]'),upload={name:'aeries-roster.txt',mimeType:'text/plain',buffer:Buffer.from(aeriesFixture)};await input.setInputFiles(upload);const dialog=page.getByRole('dialog');await expect(dialog).toContainText('2 classes found');await expect(dialog).toContainText('P3 — Government — 1 students');await expect(dialog).toContainText('P6 — Civics — 1 students');await expect(dialog).toContainText('Students found: 2');await expect(dialog).toContainText('Thomas L Almond');await expect(dialog).toContainText('170000');await page.getByRole('button',{name:'Cancel'}).click();await expect(page.getByText('Thomas L Almond')).not.toBeVisible();await input.setInputFiles(upload);await page.getByRole('button',{name:'Import selected students'}).click();await expect(page.getByText('2 selected Aeries records processed.')).toBeVisible();await expect(page.getByText('Thomas L Almond')).toBeVisible();await expect(page.getByText('Utah B Nets')).toBeVisible()});

test('water passes, usage limits, bans, counting preference, and persistent student navigation',async({page})=>{
 await page.addInitScript(()=>{let fullscreen=false;Object.defineProperty(document,'fullscreenElement',{configurable:true,get:()=>fullscreen?document.documentElement:null});Element.prototype.requestFullscreen=async()=>{fullscreen=true;document.dispatchEvent(new Event('fullscreenchange'))};document.exitFullscreen=async()=>{fullscreen=false;document.dispatchEvent(new Event('fullscreenchange'))}});await setup(page);await openTeacher(page);const returnToStudents=page.getByRole('navigation').getByRole('button',{name:'Return to student mode'});await expect(returnToStudents).toBeVisible();
 await page.getByRole('button',{name:'Roster',exact:true}).click();await expect(page.getByLabel('Ban this student from bathroom and water passes')).toHaveCount(0);await page.locator('.adminrow').filter({hasText:'Jordan Lee'}).getByRole('button',{name:'Edit'}).click();await page.getByLabel('Individual use limit').fill('1');await page.getByRole('button',{name:'Save changes'}).click();const alexRow=page.locator('.adminrow').filter({hasText:'Alex Rivera'});await alexRow.getByRole('button',{name:'Ban',exact:true}).click();await expect(alexRow).toContainText('Banned');await expect(alexRow.getByRole('button',{name:'Unban'})).toBeVisible();
 await page.getByRole('button',{name:'Settings'}).click();await page.getByLabel('Bathroom Passes').selectOption('2');await expect(page.getByText('Usage limits saved automatically.')).toBeVisible();await expect(page.getByLabel('Count completed water passes in statistics and toward use limits')).not.toBeChecked();await expect(page.getByRole('button',{name:'Save usage limits'})).not.toBeVisible();await returnToStudents.click();await page.getByRole('button',{name:'Start Bathroom Kiosk'}).click();
 await keypad(page,'001482');await page.getByRole('button',{name:/Jordan Lee/}).click();await page.getByRole('button',{name:'Add my name for water (90 seconds)'}).click();await page.getByRole('button',{name:"I'm ready to get water"}).click();await changeActiveStart(page,91);await page.reload();await page.getByRole('button',{name:'Start Bathroom Kiosk'}).click();await expect(page.getByText('Water pass over 90 seconds')).toBeVisible();await page.getByRole('button',{name:"I'm back"}).click();
 await openTeacher(page);await page.getByRole('button',{name:'Stats'}).click();await expect(page.locator('.tr').filter({hasText:'Jordan Lee'})).toContainText('0');await page.getByRole('button',{name:'Settings'}).click();await page.getByLabel('Count completed water passes in statistics and toward use limits').check();await expect(page.getByText('Usage limits saved automatically.')).toBeVisible();await page.getByRole('button',{name:'Stats'}).click();await expect(page.locator('.tr').filter({hasText:'Jordan Lee'})).toContainText('1');
 await page.getByRole('navigation').getByRole('button',{name:'Return to student mode'}).click();await page.getByRole('button',{name:'Start Bathroom Kiosk'}).click();await keypad(page,'001482');await page.getByRole('button',{name:/Jordan Lee/}).click();await page.getByRole('button',{name:'Add my name for the bathroom'}).click();await expect(page.getByText('You have reached your limit of 1 use.')).toBeVisible();await page.getByRole('button',{name:'Back to home page'}).click();await keypad(page,'001937');await page.getByRole('button',{name:/Alex Rivera/}).click();await page.getByRole('button',{name:'Add my name for the bathroom'}).click();await expect(page.getByText('Bathroom and water passes are not available for this student.')).toBeVisible();
});

test('history deletion, factory reset, and setup-screen backup recovery work',async({page},testInfo)=>{
 await setup(page);await openTeacher(page);await page.getByRole('button',{name:'Settings'}).click();
 page.once('dialog',d=>d.accept());const recoveryDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Export full backup'}).click();const recovery=await recoveryDownload;const recoveryPath=testInfo.outputPath('factory-reset-recovery.json');await recovery.saveAs(recoveryPath);
 await page.evaluate(async()=>{const request=indexedDB.open('ClassroomBathroomQueue');const database=await new Promise<IDBDatabase>((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});await new Promise<void>((resolve,reject)=>{const tx=database.transaction('sessions','readwrite');tx.objectStore('sessions').put({id:'test-session',studentId:'missing',studentName:'Fictional Student',studentIdSnapshot:'000001',queuedAt:new Date().toISOString(),startedAt:new Date().toISOString(),endedAt:new Date().toISOString(),durationSeconds:1,durationFormatted:'0:01',reachedWarning:false,overLimit:false,status:'completed'});tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});database.close()});
 await page.getByText('Advanced Data Tools').click();await page.getByRole('button',{name:'Delete Bathroom History'}).click();await expect(page.getByRole('dialog')).toContainText('Delete Bathroom History');await page.getByLabel('Confirm teacher PIN').fill('1111');await page.getByRole('button',{name:'Delete History Permanently'}).click();await expect(page.getByText('Incorrect PIN.')).toBeVisible();await page.getByLabel('Confirm teacher PIN').fill('2468');await page.getByRole('button',{name:'Delete History Permanently'}).click();await expect(page.getByText('Bathroom history deleted.')).toBeVisible();expect(await page.evaluate(async()=>{const r=indexedDB.open('ClassroomBathroomQueue');const d=await new Promise<IDBDatabase>((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});return await new Promise<number>((resolve,reject)=>{const tx=d.transaction('sessions'),q=tx.objectStore('sessions').count();q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error)})})).toBe(0);
 await page.getByRole('button',{name:'Factory Reset',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('Factory Reset');await page.getByLabel('Confirm teacher PIN').fill('2468');await page.getByLabel('I understand that all local app data will be erased.').check();await page.getByRole('button',{name:'Factory Reset Permanently'}).click();await expect(page.getByText('Create your teacher PIN')).toBeVisible();await page.getByLabel('Teacher PIN',{exact:true}).fill('8642');await page.getByLabel('Confirm PIN').fill('8642');await page.getByRole('button',{name:'Continue',exact:true}).click();await page.locator('input[type=file][accept*="json"]').setInputFiles(recoveryPath);await expect(page.getByText('Valid full backup ready')).toBeVisible();await page.getByRole('button',{name:'Confirm Restore Full Backup'}).click();await expect(page.getByText('Ready for class')).toBeVisible();await page.keyboard.press('Control+Shift+5');await page.getByLabel('Teacher PIN').fill('8642');await page.getByRole('button',{name:'Continue'}).click();await page.getByRole('button',{name:'Roster',exact:true}).click();await expect(page.getByText('Jordan Lee')).toBeVisible();
});

test('Aeries class associations, hidden schedule controls, and local-only operation',async({page})=>{
 await page.addInitScript(()=>{let fullscreen=false;Object.defineProperty(document,'fullscreenElement',{configurable:true,get:()=>fullscreen?document.documentElement:null});Element.prototype.requestFullscreen=async()=>{fullscreen=true;document.dispatchEvent(new Event('fullscreenchange'))};document.exitFullscreen=async()=>{fullscreen=false;document.dispatchEvent(new Event('fullscreenchange'))}});
 const remoteRequests:string[]=[];
 page.on('request',request=>{const url=new URL(request.url());if(!['127.0.0.1','localhost'].includes(url.hostname))remoteRequests.push(request.url())});
 await setup(page);
 await openTeacher(page);
 await page.getByRole('button',{name:'Roster',exact:true}).click();
 await page.locator('input[type=file][accept*="text/plain"]').setInputFiles({name:'aeries-roster.txt',mimeType:'text/plain',buffer:Buffer.from(aeriesFixture)});
 await page.getByRole('button',{name:'Import selected students'}).click();
 await page.getByRole('button',{name:'Settings'}).click();
 await expect(page.getByRole('heading',{name:'Switch Class / Period'})).not.toBeVisible();
 await expect(page.getByRole('heading',{name:'Bell Schedule'})).not.toBeVisible();
 const stored=await page.evaluate(async()=>{const request=indexedDB.open('ClassroomBathroomQueue');const database=await new Promise<IDBDatabase>((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});const read=(store:string)=>new Promise<any[]>((resolve,reject)=>{const tx=database.transaction(store),get=tx.objectStore(store).getAll();get.onsuccess=()=>resolve(get.result);get.onerror=()=>reject(get.error)});return{classes:await read('classes'),enrollments:await read('enrollments'),settings:(await read('settings'))[0]}});
 expect(stored.classes).toHaveLength(2);
 expect(stored.enrollments).toHaveLength(2);
 expect(remoteRequests).toEqual([]);
 await page.getByRole('navigation').getByRole('button',{name:'Return to student mode'}).click();await page.getByRole('button',{name:'Start Bathroom Kiosk'}).click();await keypad(page,'170000');await expect(page.getByRole('button',{name:/Thomas L Almond/})).toBeVisible();
});

test('Ctrl+Shift+6 clears only waiting students and Undo restores exact queue state',async({page})=>{
 await page.addInitScript(()=>{let fullscreen=false;Object.defineProperty(document,'fullscreenElement',{configurable:true,get:()=>fullscreen?document.documentElement:null});Element.prototype.requestFullscreen=async()=>{fullscreen=true;document.dispatchEvent(new Event('fullscreenchange'))};document.exitFullscreen=async()=>{fullscreen=false;document.dispatchEvent(new Event('fullscreenchange'))}});
 await setup(page);
 await page.getByRole('button',{name:'Start Bathroom Kiosk'}).click();
 await keypad(page,'001482');await page.getByRole('button',{name:/Jordan Lee/}).click();await page.getByRole('button',{name:'Add my name for the bathroom'}).click();
 await page.getByRole('button',{name:"I'm ready to use the bathroom"}).click();
 await keypad(page,'001937');await page.getByRole('button',{name:/Alex Rivera/}).click();await page.getByRole('button',{name:'Add my name for the bathroom'}).click();
 const before=await page.evaluate(async()=>{const request=indexedDB.open('ClassroomBathroomQueue'),database=await new Promise<IDBDatabase>((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});return await new Promise<any[]>((resolve,reject)=>{const tx=database.transaction('queue'),get=tx.objectStore('queue').getAll();get.onsuccess=()=>resolve(get.result);get.onerror=()=>reject(get.error)})});
 await page.keyboard.press('Control+Shift+6');
 await expect(page.getByText('1 waiting student removed.')).toBeVisible();
 await expect(page.getByRole('heading',{name:'Jordan Lee'})).toBeVisible();
 await expect(page.getByText('Alex Rivera')).not.toBeVisible();
 await page.getByRole('button',{name:'Undo'}).click();
 await expect(page.getByText('Alex Rivera')).toBeVisible();
 const after=await page.evaluate(async()=>{const request=indexedDB.open('ClassroomBathroomQueue'),database=await new Promise<IDBDatabase>((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});return await new Promise<any[]>((resolve,reject)=>{const tx=database.transaction('queue'),get=tx.objectStore('queue').getAll();get.onsuccess=()=>resolve(get.result);get.onerror=()=>reject(get.error)})});
 expect(after.sort((a,b)=>a.queuedAt.localeCompare(b.queuedAt))).toEqual(before.sort((a,b)=>a.queuedAt.localeCompare(b.queuedAt)));
});

test('teacher schedule controls are hidden while their saved data remains intact',async({page})=>{
 await setup(page);await openTeacher(page);await page.getByRole('button',{name:'Roster',exact:true}).click();await page.locator('input[type=file][accept*="text/plain"]').setInputFiles({name:'aeries-roster.txt',mimeType:'text/plain',buffer:Buffer.from(aeriesFixture)});await page.getByRole('button',{name:'Import selected students'}).click();await page.getByRole('button',{name:'Settings'}).click();
 await expect(page.getByRole('heading',{name:'Switch Class / Period'})).not.toBeVisible();
 await expect(page.getByRole('heading',{name:'Bell Schedule'})).not.toBeVisible();
 const schedules=await page.evaluate(async()=>{const request=indexedDB.open('ClassroomBathroomQueue'),database=await new Promise<IDBDatabase>((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});return await new Promise<any[]>((resolve,reject)=>{const tx=database.transaction('bellSchedules'),get=tx.objectStore('bellSchedules').getAll();get.onsuccess=()=>resolve(get.result);get.onerror=()=>reject(get.error)})});
 expect(schedules.length).toBeGreaterThan(0);
});

test('teacher can customize both kiosk keyboard shortcuts',async({page})=>{
 await page.addInitScript(()=>{let fullscreen=false;Object.defineProperty(document,'fullscreenElement',{configurable:true,get:()=>fullscreen?document.documentElement:null});Element.prototype.requestFullscreen=async()=>{fullscreen=true;document.dispatchEvent(new Event('fullscreenchange'))};document.exitFullscreen=async()=>{fullscreen=false;document.dispatchEvent(new Event('fullscreenchange'))}});
 await setup(page);await openTeacher(page);await page.getByRole('button',{name:'Settings'}).click();await page.getByLabel('Open teacher dashboard').selectOption('Ctrl+Shift+9');await page.getByLabel('Clear waiting queue').selectOption('Ctrl+Shift+7');await page.getByRole('button',{name:'Save keyboard shortcuts'}).click();await expect(page.getByText('Keyboard shortcuts saved.')).toBeVisible();await page.getByRole('navigation').getByRole('button',{name:'Return to student mode'}).click();await page.getByRole('button',{name:'Start Bathroom Kiosk'}).click();await keypad(page,'001482');await page.getByRole('button',{name:/Jordan Lee/}).click();await page.getByRole('button',{name:'Add my name for the bathroom'}).click();await page.keyboard.press('Control+Shift+6');await expect(page.getByText('Jordan Lee')).toBeVisible();await page.keyboard.press('Control+Shift+7');await expect(page.getByText('1 waiting student removed.')).toBeVisible();await page.keyboard.press('Control+Shift+9');await expect(page.getByRole('dialog').getByRole('heading',{name:'Teacher PIN'})).toBeVisible();
});
