import{test,expect,type Page}from'@playwright/test';
const aeriesFixture=`Fictional High School,Attendance Class Roster
Period,Course Title,Term,Sec#,Crs ID,Teacher,Calendar,Room,Year
P3,Government,Y,75,302745,"TEACHER, SAMPLE",P3,L207,26-27
Student ID,Student Name,GR,8/7/2026
01,170000,,"Almond, Thomas L",10,,,,
Fictional High School,Attendance Class Roster
Period,Course Title,Term,Sec#,Crs ID,Teacher,Calendar,Room,Year
P6,Civics,Y,91,302700,"TEACHER, SAMPLE",P6,L208,26-27
Student ID,Student Name,GR,8/7/2026
01,170001,,"Nets, Utah B",12,,,,`;

async function saveSetupShortcut(page:Page,shortcut='Ctrl+Shift+5'){
 await expect(page.getByRole('heading',{name:'Choose your teacher dashboard shortcut'})).toBeVisible();
 await expect(page.getByLabel('Open teacher dashboard')).toHaveValue('Ctrl+Shift+5');
 if(shortcut!=='Ctrl+Shift+5')await page.getByLabel('Open teacher dashboard').selectOption(shortcut);
 await page.getByRole('button',{name:'Save Shortcut and Continue'}).click();
}
async function setup(page:Page){
 await page.goto('/',{waitUntil:'domcontentloaded'});
 await page.getByLabel('Teacher PIN',{exact:true}).fill('2468');
 await page.getByLabel('Confirm PIN').fill('2468');
 await page.getByRole('button',{name:'Continue',exact:true}).click();
 await saveSetupShortcut(page);
 await page.getByRole('button',{name:'Add Student Manually'}).click();
 for(const [index,[name,id]]of[['Fictional Student One','001482'],['Fictional Student Two','001937']].entries()){await page.getByLabel('Full name').fill(name);await page.getByLabel('Student ID').fill(id);await page.getByRole('button',{name:'Add Student',exact:true}).click();await expect(page.getByText(`${index+1} student${index?'s':''} currently added`)).toBeVisible()}
 await page.getByRole('button',{name:'Continue to App'}).click();
 await expect(page.getByText('Ready for class')).toBeVisible();
}
async function openTeacher(page:Page){await page.keyboard.press('Control+Shift+5');await expect(page.getByRole('dialog')).toBeVisible();await page.getByLabel('Teacher PIN').fill('2468');await page.getByRole('button',{name:'Continue'}).click();await expect(page.getByText('Teacher dashboard')).toBeVisible()}
async function keypad(page:Page,id:string){await page.getByRole('button',{name:'Add/remove my name from the bathroom line'}).click();for(const digit of id)await page.locator('.keypad').getByRole('button',{name:digit,exact:true}).click();await page.getByRole('button',{name:'Find me'}).click()}
async function changeActiveStart(page:Page,secondsAgo:number){await page.evaluate(async seconds=>{const request=indexedDB.open('ClassroomBathroomQueue');const database=await new Promise<IDBDatabase>((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});await new Promise<void>((resolve,reject)=>{const tx=database.transaction('queue','readwrite'),store=tx.objectStore('queue'),all=store.getAll();all.onsuccess=()=>{const active=all.result.find((x:any)=>x.status==='active');active.startedAt=new Date(Date.now()-seconds*1000).toISOString();store.put(active)};tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});database.close()},secondsAgo)}
async function addCompletedSession(page:Page,name:string,suffix:string,overLimit=false){await page.evaluate(async({name,suffix,overLimit})=>{const request=indexedDB.open('ClassroomBathroomQueue'),database=await new Promise<IDBDatabase>((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});await new Promise<void>((resolve,reject)=>{const tx=database.transaction(['students','sessions'],'readwrite'),students=tx.objectStore('students').getAll();students.onsuccess=()=>{const student=students.result.find((value:any)=>value.name===name),endedAt=new Date().toISOString(),startedAt=new Date(Date.now()-60_000).toISOString();tx.objectStore('sessions').put({id:`probation-${suffix}`,studentId:student.id,studentName:student.name,queuedAt:startedAt,startedAt,endedAt,durationSeconds:60,durationFormatted:'1:00',reachedWarning:overLimit,overLimit,status:'completed',passType:'bathroom',createdAt:endedAt,updatedAt:endedAt})};tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});database.close()},{name,suffix,overLimit})}
async function addTimedSession(page:Page,name:string,suffix:string,durationSeconds:number,passType:'bathroom'|'water'='bathroom'){await page.evaluate(async({name,suffix,durationSeconds,passType})=>{const request=indexedDB.open('ClassroomBathroomQueue'),database=await new Promise<IDBDatabase>((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});await new Promise<void>((resolve,reject)=>{const tx=database.transaction(['students','sessions'],'readwrite'),students=tx.objectStore('students').getAll();students.onsuccess=()=>{const student=students.result.find((value:any)=>value.name===name),endedAt=new Date().toISOString(),startedAt=new Date(Date.now()-durationSeconds*1000).toISOString();tx.objectStore('sessions').put({id:`weekly-${suffix}`,studentId:student.id,studentName:student.name,queuedAt:startedAt,startedAt,endedAt,durationSeconds,durationFormatted:`${Math.floor(durationSeconds/60)}:${String(durationSeconds%60).padStart(2,'0')}`,reachedWarning:false,overLimit:false,status:'completed',passType,createdAt:endedAt,updatedAt:endedAt})};tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});database.close()},{name,suffix,durationSeconds,passType})}
async function moveAllSessionsToPreviousWeek(page:Page){await page.evaluate(async()=>{const request=indexedDB.open('ClassroomBathroomQueue'),database=await new Promise<IDBDatabase>((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});await new Promise<void>((resolve,reject)=>{const tx=database.transaction('sessions','readwrite'),store=tx.objectStore('sessions'),all=store.getAll();all.onsuccess=()=>{for(const session of all.result){for(const field of['queuedAt','startedAt','endedAt','createdAt','updatedAt'])if(session[field])session[field]=new Date(new Date(session[field]).getTime()-8*86_400_000).toISOString();store.put(session)}};tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});database.close()})}

test('first-time setup requires and persists a non-conflicting teacher shortcut before optional roster setup',async({page})=>{
 await page.goto('/',{waitUntil:'domcontentloaded'});
 await expect(page.getByRole('heading',{name:'How to download an Aeries roster'})).toHaveCount(0);
 await page.getByRole('button',{name:'Continue',exact:true}).click();await expect(page.getByRole('alert')).toContainText('at least four digits');
 await page.getByLabel('Teacher PIN',{exact:true}).fill('2468');await page.getByLabel('Confirm PIN').fill('2468');await page.getByRole('button',{name:'Continue',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Choose your teacher dashboard shortcut'})).toBeVisible();await expect(page.getByRole('heading',{name:'How to download an Aeries roster'})).toHaveCount(0);await expect(page.getByText('This shortcut opens the teacher PIN screen from student/kiosk mode.')).toBeVisible();await expect(page.getByText('Teacher Dashboard → Settings')).toBeVisible();await expect(page.getByLabel('Open teacher dashboard')).toHaveValue('Ctrl+Shift+5');await expect(page.getByText('Your selected shortcut').locator('..')).toContainText('Ctrl+Shift+5');
 await page.getByLabel('Open teacher dashboard').selectOption('Ctrl+Shift+6');await page.getByRole('button',{name:'Save Shortcut and Continue'}).click();await expect(page.getByRole('alert')).toContainText('must be different from the clear-queue shortcut');
 await page.getByLabel('Open teacher dashboard').selectOption('Ctrl+Shift+9');await expect(page.getByText('Your selected shortcut').locator('..')).toContainText('Ctrl+Shift+9');await page.getByRole('button',{name:'Save Shortcut and Continue'}).click();
 await expect(page.getByRole('heading',{name:'Set up your roster'})).toBeVisible();const instructions=page.locator('.aeries-instructions');await expect(instructions.getByRole('heading',{name:'How to download an Aeries roster'})).toBeVisible();await expect(instructions.getByText('View Screenshot 1')).toBeVisible();await expect(instructions.getByText('View Screenshot 2')).toBeVisible();await expect(instructions.getByAltText('Aeries Reports page with an arrow pointing to Class Rosters')).toHaveAttribute('src','./aeries-step-2.png');await expect(instructions.getByAltText('Aeries Class Roster settings showing TXT, One Day, and unchecked options')).toHaveAttribute('src','./aeries-step-3.png');await expect(page.getByRole('button',{name:'Import Aeries Class Roster'})).toBeVisible();await expect(page.getByRole('button',{name:'Import Standard Roster'})).toBeVisible();await expect(page.getByRole('button',{name:'Add Student Manually'})).toBeVisible();await expect(page.getByRole('button',{name:'Restore Full Backup'})).toBeVisible();
 await page.getByRole('button',{name:'Continue Without Students'}).click();await expect(page.getByText('Ready for class')).toBeVisible();await page.reload();await expect(page.getByText('Ready for class')).toBeVisible();await expect(page.getByRole('heading',{name:'Create teacher PIN'})).toHaveCount(0);await page.getByRole('button',{name:'Start Bathroom Kiosk'}).click();await expect(page.getByText('No students have been added yet.')).toBeVisible();await expect(page.getByText('Use teacher settings to import or add a roster.')).toBeVisible();
 await page.keyboard.press('Control+Shift+5');await expect(page.getByRole('dialog')).toHaveCount(0);await page.keyboard.press('Control+Shift+9');await expect(page.getByRole('dialog').getByRole('heading',{name:'Teacher PIN'})).toBeVisible();
});
test('new teacher can import Aeries during setup without a temporary student',async({page})=>{
 await page.goto('/',{waitUntil:'domcontentloaded'});await page.getByLabel('Teacher PIN',{exact:true}).fill('2468');await page.getByLabel('Confirm PIN').fill('2468');await page.getByRole('button',{name:'Continue',exact:true}).click();
 await saveSetupShortcut(page);
 await page.locator('input[type=file][accept*="text/plain"]').setInputFiles({name:'aeries-roster.txt',mimeType:'text/plain',buffer:Buffer.from(aeriesFixture)});await page.getByRole('button',{name:'Import selected students'}).click();await expect(page.getByText('2 selected Aeries records processed.')).toBeVisible();await page.getByRole('button',{name:'Continue to App'}).click();await expect(page.getByText('Ready for class')).toBeVisible();
});

test('existing configured teachers see the probation release notice once without losing data or restarting setup',async({page})=>{
 await setup(page);await page.getByRole('button',{name:'Start Bathroom Kiosk'}).click();await keypad(page,'001937');await page.getByRole('button',{name:'Add my name for the bathroom'}).click();await addCompletedSession(page,'Fictional Student One','release-preserved');await page.evaluate(async()=>{const request=indexedDB.open('ClassroomBathroomQueue'),database=await new Promise<IDBDatabase>((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});await new Promise<void>((resolve,reject)=>{const tx=database.transaction('settings','readwrite'),store=tx.objectStore('settings'),get=store.get('settings');get.onsuccess=()=>{const value=get.result;delete value.lastSeenReleaseId;store.put(value)};tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});database.close()});await page.reload();
 const release=page.getByRole('dialog');await expect(release.getByRole('heading',{name:'New: Pass Suspension and weekly bathroom-time limits'})).toBeVisible();await expect(release).toContainText('disabled by default');await expect(release).toContainText('individual weekly overrides or unlimited time');await expect(page.getByRole('heading',{name:'Create teacher PIN'})).toHaveCount(0);await release.getByRole('button',{name:'Got it'}).click();await expect(release).toHaveCount(0);await page.reload();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByText('Ready for class')).toBeVisible();await openTeacher(page);await expect(page.getByText(/#1 Fictional Student Two/)).toBeVisible();await page.getByRole('button',{name:'Stats'}).click();await expect(page.locator('.tr').filter({hasText:'Fictional Student One'})).toContainText('1');await page.getByRole('button',{name:'Roster',exact:true}).click();await expect(page.getByText('Fictional Student One')).toBeVisible();
});

test('overtime warnings, automatic suspension, teacher overrides, backup restore, expiry, and offline use',async({page,context},testInfo)=>{
 testInfo.setTimeout(120_000);
 await setup(page);await openTeacher(page);await page.getByRole('button',{name:'Pass Suspension',exact:true}).click();await expect(page.getByRole('heading',{name:'Automatic Pass Suspensions'})).toHaveCount(0);await expect(page.locator('details.pass-suspension-advanced')).toHaveCount(0);await page.getByRole('button',{name:'Usage Limit',exact:true}).click();await expect(page.getByRole('radio',{name:/Bathroom Passes/})).toBeChecked();const automaticDetails=page.locator('details.bathroom-pass-advanced');await expect(automaticDetails).not.toHaveAttribute('open','');await expect(page.getByRole('heading',{name:'Automatic Pass Suspensions'})).not.toBeVisible();await automaticDetails.getByText('Advanced',{exact:true}).click();await expect(page.getByLabel('Enable overtime-count warnings')).not.toBeChecked();await expect(page.getByLabel('Enable automatic pass suspensions')).not.toBeChecked();
 await page.getByLabel('Enable overtime-count warnings').check();await page.getByLabel('Enable automatic pass suspensions').check();await page.getByLabel('I understand and will provide emergency and accommodation overrides.').click();await page.getByLabel('Overtime-count warning threshold').fill('1');await page.getByLabel('Overtime-count suspension threshold').fill('2');await expect(page.getByRole('group',{name:'Completed uses'})).toHaveCount(0);await expect(page.getByText('Overtime percentage')).toHaveCount(0);await page.getByRole('button',{name:'Save Automatic Suspension Settings'}).click();await expect(page.getByText('Automatic pass suspension settings saved.')).toBeVisible();
 await addCompletedSession(page,'Fictional Student One','one',true);await page.reload();await page.getByRole('button',{name:'Start Bathroom Kiosk'}).click();await keypad(page,'001482');await expect(page.getByText(/1 more over-limit return within the rolling 30-day period/)).toBeVisible();await expect(page.getByRole('button',{name:'Add my name for the bathroom'})).toBeVisible();await page.getByRole('button',{name:'Back to home page'}).click();
 await addCompletedSession(page,'Fictional Student One','two',true);await page.reload();await page.getByRole('button',{name:'Start Bathroom Kiosk'}).click();await keypad(page,'001482');await expect(page.getByRole('heading',{name:'Bathroom-pass access in this app is temporarily suspended'})).toBeVisible();await expect(page.getByText('Raw overtime threshold (2)')).toBeVisible();await expect(page.getByText('Speak with your teacher if this is an emergency or you have an accommodation.')).toBeVisible();await expect(page.getByRole('button',{name:'Add my name for the bathroom'})).toHaveCount(0);
 await page.evaluate(async()=>{await navigator.serviceWorker.ready});await context.setOffline(true);await page.reload();await expect(page.getByText('Ready for class')).toBeVisible();await page.getByRole('button',{name:'Start Bathroom Kiosk'}).click();await keypad(page,'001482');await expect(page.getByRole('heading',{name:'Bathroom-pass access in this app is temporarily suspended'})).toBeVisible();await context.setOffline(false);
 await openTeacher(page);await page.getByRole('button',{name:'Pass Suspension',exact:true}).click();const row=page.locator('.probation-row').filter({hasText:'Fictional Student One'});await expect(row).toContainText('Raw overtime count2');await expect(row).toContainText('Rolling 30-day automatic suspension');await expect(row).toContainText('Raw overtime threshold (2)');
 await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Export Encrypted Full Backup'}).click();await page.getByLabel('Backup password',{exact:true}).fill('correct horse battery');await page.getByLabel('Confirm backup password').fill('correct horse battery');const downloadReady=page.waitForEvent('download');await page.getByRole('button',{name:'Encrypt and Download'}).click();const download=await downloadReady,backupPath=testInfo.outputPath('probation-backup.json');await download.saveAs(backupPath);
 await page.getByRole('button',{name:'Pass Suspension',exact:true}).click();await row.getByRole('button',{name:'End suspension'}).click();await page.getByLabel('Confirm teacher PIN').fill('2468');await page.getByRole('button',{name:'Confirm change'}).click();await expect(page.locator('.probation-row').filter({hasText:'Fictional Student One'})).toHaveCount(0);await page.reload();await openTeacher(page);await page.getByRole('button',{name:'Pass Suspension',exact:true}).click();await expect(page.locator('.probation-row').filter({hasText:'Fictional Student One'})).toHaveCount(0);
 await page.getByRole('button',{name:'Settings',exact:true}).click();await page.locator('input[type=file][accept*="json"]').setInputFiles(backupPath);await page.getByLabel('Backup password',{exact:true}).fill('correct horse battery');await page.getByLabel('Restore teacher PIN').fill('2468');await page.getByRole('button',{name:'Restore and Replace Current Data'}).click();await expect(page.getByText('Encrypted backup restored successfully.')).toBeVisible();await page.getByRole('button',{name:'Usage Limit',exact:true}).click();await page.locator('details.bathroom-pass-advanced').getByText('Advanced',{exact:true}).click();await expect(page.getByLabel('Enable automatic pass suspensions')).toBeChecked();await page.getByRole('button',{name:'Pass Suspension',exact:true}).click();const restoredRow=page.locator('.probation-row').filter({hasText:'Fictional Student One'});await expect(restoredRow).toContainText('Rolling 30-day automatic suspension');
 await page.evaluate(async()=>{const request=indexedDB.open('ClassroomBathroomQueue'),database=await new Promise<IDBDatabase>((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});await new Promise<void>((resolve,reject)=>{const tx=database.transaction('students','readwrite'),store=tx.objectStore('students'),all=store.getAll();all.onsuccess=()=>{const student=all.result.find((value:any)=>value.name==='Fictional Student One');student.passSuspension.endsAt=new Date(Date.now()-1000).toISOString();store.put(student)};tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});database.close()});await page.reload();await page.getByRole('button',{name:'Start Bathroom Kiosk'}).click();await keypad(page,'001482');await expect(page.getByRole('heading',{name:'Bathroom-pass access in this app is temporarily suspended'})).toHaveCount(0);await expect(page.getByRole('button',{name:'Add my name for the bathroom'})).toBeVisible();
});

test('overtime warnings stay hidden when disabled or when weekly time is selected',async({page})=>{
 await setup(page);await addCompletedSession(page,'Fictional Student One','disabled-one',true);await addCompletedSession(page,'Fictional Student One','disabled-two',true);await page.reload();await page.getByRole('button',{name:'Start Bathroom Kiosk'}).click();await keypad(page,'001482');await expect(page.locator('.probation-warning')).toHaveCount(0);await page.getByRole('button',{name:'Back to home page'}).click();await openTeacher(page);await page.getByRole('button',{name:'Pass Suspension',exact:true}).click();await expect(page.locator('.probation-row').filter({hasText:'Fictional Student One'})).toHaveCount(0);
 await page.getByRole('button',{name:'Usage Limit',exact:true}).click();await page.locator('details.bathroom-pass-advanced').getByText('Advanced',{exact:true}).click();await page.getByLabel('Enable overtime-count warnings').check();await page.getByRole('button',{name:'Save Automatic Suspension Settings'}).click();await page.getByRole('navigation').getByRole('button',{name:'Return to student mode'}).click();await page.getByRole('button',{name:'Start Bathroom Kiosk'}).click();await keypad(page,'001482');await expect(page.getByText('WARNING: You are approaching the teacher’s overtime review limit. Please return on time.')).toBeVisible();
 await page.getByRole('button',{name:'Back to home page'}).click();await openTeacher(page);await page.getByRole('button',{name:'Usage Limit',exact:true}).click();await page.getByRole('radio',{name:/Weekly Bathroom Time/}).check();await expect(page.getByText('Weekly Bathroom Time selected. Only this usage limit is active.')).toBeVisible();await page.getByRole('navigation').getByRole('button',{name:'Return to student mode'}).click();await page.getByRole('button',{name:'Start Bathroom Kiosk'}).click();await keypad(page,'001482');await expect(page.getByText(/approaching the teacher’s overtime review limit/)).toHaveCount(0);await page.getByRole('button',{name:'Back to home page'}).click();await openTeacher(page);await page.getByRole('button',{name:'Pass Suspension',exact:true}).click();await expect(page.locator('.probation-row').filter({hasText:'Fictional Student One'})).toHaveCount(0);
});

test('weekly allowance shows exact remaining time, resets, suspends on overage, survives offline use, and restores from backup',async({page,context},testInfo)=>{
 testInfo.setTimeout(150_000);
 await setup(page);await openTeacher(page);await page.getByRole('button',{name:'Usage Limit',exact:true}).click();
 await expect(page.getByRole('radio',{name:/Bathroom Passes/})).toBeChecked();await page.getByRole('radio',{name:/Weekly Bathroom Time/}).check();await expect(page.getByText('Weekly Bathroom Time selected. Only this usage limit is active.')).toBeVisible();const weeklyAdvanced=page.locator('details.weekly-time-advanced');await expect(weeklyAdvanced).not.toHaveAttribute('open','');await expect(page.getByLabel('Automatically suspend pass if student exceeds weekly limit')).not.toBeVisible();await expect(page.getByLabel('Weekly allowance (minutes)')).toHaveValue('20');await expect(page.getByLabel('Weekly reset day')).toHaveValue('1');await page.getByLabel('Warn student when remaining time is at or below (minutes)').fill('8');
 await page.getByRole('button',{name:'Save weekly bathroom-time settings'}).click();await expect(page.getByText('Weekly bathroom-time settings saved.')).toBeVisible();
 await addTimedSession(page,'Fictional Student One','twelve',720);await page.reload();await page.getByRole('button',{name:'Start Bathroom Kiosk'}).click();await keypad(page,'001482');const weekly=page.getByLabel('Weekly bathroom time');await expect(weekly).toContainText('Allowance20 minutes');await expect(weekly).toContainText('Used12 minutes');await expect(weekly).toContainText('Remaining8 minutes');await expect(page.getByText('You have 8 minutes of bathroom time remaining this week.')).toBeVisible();await expect(page.getByRole('button',{name:'Add my name for the bathroom'})).toBeEnabled();
 await page.getByRole('button',{name:'Add my name for the bathroom'}).click();await keypad(page,'001482');page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Remove my name from the bathroom line'}).click();
 await addTimedSession(page,'Fictional Student One','eight',480);await page.reload();await page.getByRole('button',{name:'Start Bathroom Kiosk'}).click();await keypad(page,'001482');await expect(weekly).toContainText('Used20 minutes');await expect(weekly).toContainText('Remaining0 seconds');await expect(weekly).toContainText('Resets');await expect(weekly).toContainText('Speak with your teacher if this is an emergency or you have an accommodation.');await expect(page.locator('.weekly-time-warning')).toHaveCount(0);await expect(page.getByRole('button',{name:'Add my name for the bathroom'})).toBeDisabled();await expect(page.getByRole('button',{name:/water/i})).toHaveCount(0);
 await moveAllSessionsToPreviousWeek(page);await page.reload();await page.getByRole('button',{name:'Start Bathroom Kiosk'}).click();await keypad(page,'001482');await expect(weekly).toContainText('Used0 seconds');await expect(weekly).toContainText('Remaining20 minutes');await expect(page.getByRole('button',{name:'Add my name for the bathroom'})).toBeEnabled();
 await page.getByRole('button',{name:'Back to home page'}).click();await openTeacher(page);await page.getByRole('button',{name:'Usage Limit',exact:true}).click();await page.locator('details.weekly-time-advanced').getByText('Advanced',{exact:true}).click();await page.getByLabel('Automatically suspend pass if student exceeds weekly limit').check();await page.getByLabel('I understand and will provide emergency and accommodation overrides.').check();await page.getByLabel('Minutes over before suspension').fill('1');await page.getByRole('button',{name:'Save weekly bathroom-time settings'}).click();await expect(page.getByText('Weekly bathroom-time settings saved.')).toBeVisible();
 await page.getByRole('navigation').getByRole('button',{name:'Return to student mode'}).click();await page.getByRole('button',{name:'Start Bathroom Kiosk'}).click();await keypad(page,'001482');await page.getByRole('button',{name:'Add my name for the bathroom'}).click();await page.getByRole('button',{name:"I'm ready to use the bathroom"}).click();await changeActiveStart(page,1260);await page.getByRole('button',{name:"I'm back"}).click();await keypad(page,'001482');await expect(page.getByRole('heading',{name:'Bathroom-pass access in this app is temporarily suspended'})).toBeVisible();await expect(page.getByText(/Weekly bathroom-time allowance exceeded by/)).toBeVisible();await expect(page.getByRole('button',{name:'Add my name for the bathroom'})).toHaveCount(0);
 await page.evaluate(async()=>{await navigator.serviceWorker.ready});await context.setOffline(true);await page.reload();await expect(page.getByText('Ready for class')).toBeVisible();await page.getByRole('button',{name:'Start Bathroom Kiosk'}).click();await keypad(page,'001482');await expect(page.getByRole('heading',{name:'Bathroom-pass access in this app is temporarily suspended'})).toBeVisible();await context.setOffline(false);
 await openTeacher(page);await page.getByRole('button',{name:'Pass Suspension',exact:true}).click();let row=page.locator('.probation-row').filter({hasText:'Fictional Student One'});await expect(row).toContainText('Weekly-time automatic suspension');await expect(row).toContainText('Weekly used');await expect(row).toContainText('Weekly overage');
 await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Export Encrypted Full Backup'}).click();await page.getByLabel('Backup password',{exact:true}).fill('correct horse battery');await page.getByLabel('Confirm backup password').fill('correct horse battery');const downloadReady=page.waitForEvent('download');await page.getByRole('button',{name:'Encrypt and Download'}).click();const download=await downloadReady,backupPath=testInfo.outputPath('weekly-backup.json');await download.saveAs(backupPath);
 await page.getByRole('button',{name:'Pass Suspension',exact:true}).click();row=page.locator('.probation-row').filter({hasText:'Fictional Student One'});await row.getByRole('button',{name:'End suspension'}).click();await page.getByLabel('Confirm teacher PIN').fill('2468');await page.getByRole('button',{name:'Confirm change'}).click();await page.getByRole('button',{name:'Settings',exact:true}).click();await page.locator('input[type=file][accept*="json"]').setInputFiles(backupPath);await page.getByLabel('Backup password',{exact:true}).fill('correct horse battery');await page.getByLabel('Restore teacher PIN').fill('2468');await page.getByRole('button',{name:'Restore and Replace Current Data'}).click();await expect(page.getByText('Encrypted backup restored successfully.')).toBeVisible();await page.getByRole('button',{name:'Usage Limit',exact:true}).click();await expect(page.getByRole('radio',{name:/Weekly Bathroom Time/})).toBeChecked();await page.locator('details.weekly-time-advanced').getByText('Advanced',{exact:true}).click();await expect(page.getByLabel('Automatically suspend pass if student exceeds weekly limit')).toBeChecked();await expect(page.getByLabel('Warn student when remaining time is at or below (minutes)')).toHaveValue('8');await page.getByRole('button',{name:'Pass Suspension',exact:true}).click();row=page.locator('.probation-row').filter({hasText:'Fictional Student One'});await expect(row).toContainText('Weekly-time automatic suspension');
});

test('weekly student overrides work while legacy water records remain compatible and hidden from controls',async({page})=>{
 await setup(page);await openTeacher(page);await page.getByRole('button',{name:'Usage Limit',exact:true}).click();await page.getByRole('radio',{name:/Weekly Bathroom Time/}).check();await expect(page.getByText('Weekly Bathroom Time selected. Only this usage limit is active.')).toBeVisible();await page.getByRole('button',{name:'Save weekly bathroom-time settings'}).click();
 await page.getByRole('button',{name:'Roster',exact:true}).click();let row=page.locator('.adminrow').filter({hasText:'Fictional Student One'});await row.getByRole('button',{name:'Edit'}).click();await page.getByLabel('Weekly bathroom-time allowance').selectOption('override');await page.getByLabel('Individual weekly allowance (minutes)').fill('10');await page.getByRole('button',{name:'Save changes'}).click();await expect(row).toContainText('Weekly time: 10 minutes');await addTimedSession(page,'Fictional Student One','override-ten',600);await page.reload();
 await page.getByRole('button',{name:'Start Bathroom Kiosk'}).click();await keypad(page,'001482');let weekly=page.getByLabel('Weekly bathroom time');await expect(weekly).toContainText('Allowance10 minutes');await expect(weekly).toContainText('Remaining0 seconds');await expect(page.getByRole('button',{name:'Add my name for the bathroom'})).toBeDisabled();await expect(page.getByRole('button',{name:/water/i})).toHaveCount(0);
 await page.getByRole('button',{name:'Back to home page'}).click();await openTeacher(page);await page.getByRole('button',{name:'Roster',exact:true}).click();row=page.locator('.adminrow').filter({hasText:'Fictional Student One'});await row.getByRole('button',{name:'Edit'}).click();await page.getByLabel('Weekly bathroom-time allowance').selectOption('unlimited');await page.getByRole('button',{name:'Save changes'}).click();await expect(row).toContainText('Weekly time: unlimited');await page.getByRole('navigation').getByRole('button',{name:'Return to student mode'}).click();await page.getByRole('button',{name:'Start Bathroom Kiosk'}).click();await keypad(page,'001482');weekly=page.getByLabel('Weekly bathroom time');await expect(weekly).toContainText('AllowanceUnlimited');await expect(weekly).toContainText('RemainingUnlimited');await expect(page.getByRole('button',{name:'Add my name for the bathroom'})).toBeEnabled();
 await page.getByRole('button',{name:'Back to home page'}).click();await addTimedSession(page,'Fictional Student Two','water-twenty',1200,'water');await page.reload();await page.getByRole('button',{name:'Start Bathroom Kiosk'}).click();await keypad(page,'001937');weekly=page.getByLabel('Weekly bathroom time');await expect(weekly).toContainText('Used0 seconds');await expect(page.getByRole('button',{name:/water/i})).toHaveCount(0);await page.getByRole('button',{name:'Back to home page'}).click();await openTeacher(page);await page.getByRole('button',{name:'Settings'}).click();await expect(page.getByLabel('Count completed water passes in statistics and toward use limits')).toHaveCount(0);
});

test('teacher can suspend any rostered student from Pass Suspension with PIN confirmation',async({page})=>{
 await setup(page);await openTeacher(page);await page.getByRole('button',{name:'Pass Suspension',exact:true}).click();const temporarySettings=page.locator('.manual-suspension-settings');await temporarySettings.getByLabel('Select student').selectOption({label:'Fictional Student Two — ID ending in 1937'});await temporarySettings.getByLabel('Suspension duration (days)').fill('3');await temporarySettings.getByRole('button',{name:'Apply Temporary Suspension'}).click();const dialog=page.getByRole('dialog');await expect(dialog.getByRole('heading',{name:'Confirm temporary suspension'})).toBeVisible();await dialog.getByLabel('Confirm teacher PIN').fill('1111');await dialog.getByRole('button',{name:'Confirm temporary suspension'}).click();await expect(dialog.getByRole('alert')).toContainText('Incorrect PIN.');await dialog.getByLabel('Confirm teacher PIN').fill('2468');await dialog.getByRole('button',{name:'Confirm temporary suspension'}).click();await expect(page.getByText('Fictional Student Two: temporary suspension applied.')).toBeVisible();
 let row=page.locator('.probation-row').filter({hasText:'Fictional Student Two'});await expect(row).toContainText('Temporary suspension');await row.getByRole('button',{name:'Adjust suspension'}).click();await page.getByLabel('Suspension days from now').fill('2');await page.getByLabel('Confirm teacher PIN').fill('2468');await page.getByRole('button',{name:'Confirm change'}).click();await expect(page.getByText('Fictional Student Two: suspension adjustment completed.')).toBeVisible();row=page.locator('.probation-row').filter({hasText:'Fictional Student Two'});await row.getByRole('button',{name:'End suspension'}).click();await page.getByLabel('Confirm teacher PIN').fill('2468');await page.getByRole('button',{name:'Confirm change'}).click();await expect(page.locator('.probation-row').filter({hasText:'Fictional Student Two'})).toHaveCount(0);
});

test('Student ID entry accepts top-row keys, numpad keys, editing keys, and preserves app shortcuts',async({page})=>{
 await setup(page);await page.getByRole('button',{name:'Start Bathroom Kiosk'}).click();await page.getByRole('button',{name:'Add/remove my name from the bathroom line'}).click();const field=page.getByLabel('Student ID');
 await page.keyboard.press('Digit0');await page.keyboard.press('Digit0');await expect(field).toHaveValue('••');await page.keyboard.press('Control+Shift+6');await expect(field).toHaveValue('••');await page.keyboard.press('Control+Shift+5');const teacherDialog=page.getByRole('dialog');await expect(teacherDialog.getByRole('heading',{name:'Teacher PIN'})).toBeVisible();await teacherDialog.getByRole('button',{name:'Cancel'}).click();await expect(field).toHaveValue('••');await page.keyboard.press('Escape');await expect(field).toHaveValue('');
 for(const digit of'999999')await page.keyboard.press(`Digit${digit}`);await page.keyboard.press('Enter');await expect(page.getByRole('alert')).toHaveText('Student ID not found');await page.keyboard.press('Digit7');await expect(field).toHaveValue('•');await page.keyboard.press('Escape');await expect(field).toHaveValue('');await expect(page.getByRole('alert')).toHaveCount(0);
 for(const digit of'0014827')await page.keyboard.press(`Digit${digit}`);await expect(field).toHaveValue('•••••••');await page.keyboard.press('Backspace');await expect(field).toHaveValue('••••••');await page.keyboard.press('Enter');await expect(page.getByRole('heading',{name:'Fictional Student One'})).toBeVisible();
 await page.getByRole('button',{name:'Back to home page'}).click();await page.getByRole('button',{name:'Add/remove my name from the bathroom line'}).click();for(const digit of'001937')await page.keyboard.press(`Numpad${digit}`);await expect(field).toHaveValue('••••••');await page.keyboard.press('NumpadEnter');await expect(page.getByRole('heading',{name:'Fictional Student Two'})).toBeVisible();
 await page.getByRole('button',{name:'Back to home page'}).click();await keypad(page,'001482');await expect(page.getByRole('heading',{name:'Fictional Student One'})).toBeVisible();
});

test('student kiosk flow, number pad, queue rules, thresholds, refresh, history, and removal',async({page})=>{
 await page.addInitScript(()=>{let fullscreen=false;Object.defineProperty(document,'fullscreenElement',{configurable:true,get:()=>fullscreen?document.documentElement:null});Element.prototype.requestFullscreen=async()=>{fullscreen=true;document.dispatchEvent(new Event('fullscreenchange'))};document.exitFullscreen=async()=>{fullscreen=false;document.dispatchEvent(new Event('fullscreenchange'))}});
 await setup(page);
 await page.getByRole('button',{name:'Start Bathroom Kiosk'}).click();await expect(page.getByText('The bathroom line is currently empty.')).toBeVisible();await expect(page.getByRole('button',{name:'Add/remove my name from the bathroom line'})).toHaveCSS('background-color','rgb(180, 35, 44)');
 await page.evaluate(()=>document.exitFullscreen());await expect(page.getByText('Bathroom kiosk is paused.')).toBeVisible();await expect(page.getByText('The bathroom line is currently empty.')).not.toBeVisible();await page.getByRole('button',{name:'Return to fullscreen'}).click();
 await keypad(page,'001482');await expect(page.getByRole('heading',{name:'Fictional Student One'})).toBeVisible();await page.getByRole('button',{name:'Add my name for the bathroom'}).click();await expect(page.getByRole('heading',{name:'Fictional Student One'})).toBeVisible();
 await keypad(page,'001937');await expect(page.getByRole('heading',{name:'Fictional Student Two'})).toBeVisible();await page.getByRole('button',{name:'Add my name for the bathroom'}).click();await expect(page.locator('.queue li').nth(0)).toContainText('Fictional Student One');await expect(page.locator('.queue li').nth(1)).toContainText('Fictional Student Two');
 await page.getByRole('button',{name:"I'm ready to use the bathroom"}).click();await expect(page.getByText('Your bathroom timer has started.')).toBeVisible();await expect(page.getByRole('button',{name:"I'm back"})).toHaveCSS('background-color','rgb(23, 105, 170)');
 await changeActiveStart(page,301);await page.reload();await page.getByRole('button',{name:'Start Bathroom Kiosk'}).click();await expect(page.getByText('5-minute warning')).toBeVisible();await expect(page.locator('.timer')).toHaveClass(/warning/);
 await changeActiveStart(page,421);await page.reload();await page.getByRole('button',{name:'Start Bathroom Kiosk'}).click();await expect(page.getByText('Over time limit')).toBeVisible();await expect(page.locator('.timer')).toHaveClass(/over/);
 await page.getByRole('button',{name:"I'm back"}).click();await expect(page.getByText('Welcome back.')).toBeVisible();await expect(page.getByRole('heading',{name:'Fictional Student Two'})).toBeVisible();await expect(page.getByText('Waiting to start')).toBeVisible();expect(await page.evaluate(()=>Boolean(document.fullscreenElement))).toBe(true);
 await keypad(page,'001937');await expect(page.getByRole('heading',{name:'Fictional Student Two'})).toBeVisible();page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Remove my name from the bathroom line'}).click();await expect(page.getByText('The bathroom line is currently empty.')).toBeVisible();
 await openTeacher(page);await page.getByRole('button',{name:'Stats'}).click();const jordanStats=page.locator('.tr').filter({hasText:'Fictional Student One'}),headings=page.locator('.tr.head');await expect(jordanStats).toContainText('1');await expect(headings).toContainText('Completed uses');await expect(headings).toContainText('Over-limit uses');await expect(headings).toContainText('Over %');await expect(headings).not.toContainText('Warning / over');await expect(headings).not.toContainText('Uses / canceled');
});

test('teacher access, permanent roster storage, exports, backup restore, and offline shell',async({page,context},testInfo)=>{
 await setup(page);await page.reload();await expect(page.getByText('Ready for class')).toBeVisible();
 await page.keyboard.press('Control+Shift+5');await page.getByLabel('Teacher PIN').fill('1111');await page.getByRole('button',{name:'Continue'}).click();await expect(page.getByText('Incorrect PIN.')).toBeVisible();await page.getByLabel('Teacher PIN').fill('2468');await page.getByRole('button',{name:'Continue'}).click();
 await page.getByRole('button',{name:'Roster'}).click();await expect(page.getByText('Fictional Student One')).toBeVisible();
 await page.getByRole('button',{name:'Settings'}).click();await page.getByRole('button',{name:'Export Encrypted Full Backup'}).click();await page.getByLabel('Backup password',{exact:true}).fill('correct horse battery');await page.getByLabel('Confirm backup password').fill('correct horse battery');const backupDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Encrypt and Download'}).click();const backup=await backupDownload;const backupPath=testInfo.outputPath('backup.json');await backup.saveAs(backupPath);const backupText=await (await import('node:fs/promises')).readFile(backupPath,'utf8'),backupJson=JSON.parse(backupText);expect(backupJson).toMatchObject({format:'classroom-bathroom-queue-encrypted',backupVersion:4,schemaVersion:4});for(const sensitive of['Fictional Student One','Fictional Student Two','001482','001937','2468','externalIdHash','lookupSecret','pinHash','startedAt'])expect(backupText).not.toContain(sensitive);
 await expect(page.getByRole('button',{name:'Export Name-Only Roster CSV'})).not.toBeVisible();await page.getByText('Advanced Data Tools').click();const rosterDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Export Name-Only Roster CSV'}).click();const roster=await rosterDownload;const rosterPath=testInfo.outputPath('roster.csv');await roster.saveAs(rosterPath);const rosterText=await (await import('node:fs/promises')).readFile(rosterPath,'utf8');expect(rosterText).toContain('"Fictional Student One"');expect(rosterText).not.toMatch(/001482|1482|studentId/i);
 const historyDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Export Bathroom History CSV'}).click();const history=await historyDownload;const historyPath=testInfo.outputPath('history.csv');await history.saveAs(historyPath);expect(await (await import('node:fs/promises')).readFile(historyPath,'utf8')).toMatch(/^studentName,queuedAt/);
 await page.getByRole('button',{name:'Roster',exact:true}).click();page.once('dialog',d=>d.accept());await page.locator('.adminrow').filter({hasText:'Fictional Student One'}).getByRole('button',{name:'Delete'}).click();await expect(page.getByText('Fictional Student One')).not.toBeVisible();
 await page.getByRole('button',{name:'Settings'}).click();await page.locator('input[type=file][accept*="json"]').setInputFiles(backupPath);await expect(page.getByRole('dialog')).toContainText('Restore Full Backup?');await page.getByLabel('Backup password',{exact:true}).fill('correct horse battery');await page.getByLabel('Restore teacher PIN').fill('1111');await page.getByRole('button',{name:'Restore and Replace Current Data'}).click();await expect(page.getByText('Incorrect teacher PIN.')).toBeVisible();await page.getByLabel('Restore teacher PIN').fill('2468');await page.getByRole('button',{name:'Restore and Replace Current Data'}).click();await expect(page.getByText('Encrypted backup restored successfully.')).toBeVisible();await page.getByRole('button',{name:'Roster',exact:true}).click();await expect(page.getByText('Fictional Student One')).toBeVisible();
 await page.evaluate(async()=>{await navigator.serviceWorker.ready});await context.setOffline(true);await page.reload();await expect(page.getByText('Classroom Bathroom Queue')).toBeVisible();await expect(page.getByText('Teacher welcome')).toBeVisible();await context.setOffline(false);
});

test('Aeries TXT preview covers all classes, cancel is safe, and selected students import',async({page})=>{await setup(page);await openTeacher(page);await page.getByRole('button',{name:'Roster',exact:true}).click();const instructions=page.locator('.aeries-instructions');await expect(instructions.getByRole('heading',{name:'How to download an Aeries roster'})).toBeVisible();await expect(instructions.getByText('View Screenshot 1')).toBeVisible();await expect(instructions.getByText('View Screenshot 2')).toBeVisible();const input=page.locator('input[type=file][accept*="text/plain"]'),upload={name:'aeries-roster.txt',mimeType:'text/plain',buffer:Buffer.from(aeriesFixture)};await input.setInputFiles(upload);const dialog=page.getByRole('dialog');await expect(dialog).toContainText('2 classes found');await expect(dialog).toContainText('P3 — Government — 1 students');await expect(dialog).toContainText('P6 — Civics — 1 students');await expect(dialog).toContainText('Students found: 2');await expect(dialog).toContainText('Thomas L Almond');await expect(dialog).toContainText('170000');await page.getByRole('button',{name:'Cancel'}).click();await expect(page.getByText('Thomas L Almond')).not.toBeVisible();await input.setInputFiles(upload);await page.getByRole('button',{name:'Import selected students'}).click();await expect(page.getByText('2 selected Aeries records processed.')).toBeVisible();await expect(page.getByText('Thomas L Almond')).toBeVisible();await expect(page.getByText('Utah B Nets')).toBeVisible()});

test('teacher tabs are organized, water controls are hidden, and temporary suspension replaces a permanent ban',async({page})=>{
 await page.addInitScript(()=>{let fullscreen=false;Object.defineProperty(document,'fullscreenElement',{configurable:true,get:()=>fullscreen?document.documentElement:null});Element.prototype.requestFullscreen=async()=>{fullscreen=true;document.dispatchEvent(new Event('fullscreenchange'))};document.exitFullscreen=async()=>{fullscreen=false;document.dispatchEvent(new Event('fullscreenchange'))}});await setup(page);await openTeacher(page);const navigation=page.getByRole('navigation',{name:'Teacher dashboard sections'}),returnToStudents=navigation.getByRole('button',{name:'Return to student mode'});await expect(navigation.getByRole('button',{name:'Usage Limit',exact:true})).toBeVisible();await expect(navigation.getByRole('button',{name:'Pass Suspension',exact:true})).toBeVisible();await expect(navigation.getByRole('button',{name:'Probation',exact:true})).toHaveCount(0);await expect(returnToStudents).toBeVisible();
 await navigation.getByRole('button',{name:'Settings'}).click();await expect(page.getByRole('heading',{name:'Automatic Pass Suspensions'})).toHaveCount(0);await expect(page.getByRole('heading',{name:'Temporary Suspensions'})).toHaveCount(0);await expect(page.getByLabel('Bathroom Passes')).toHaveCount(0);await expect(page.getByLabel('Warning Threshold (minutes)')).toHaveCount(0);await expect(page.getByLabel('Count completed water passes in statistics and toward use limits')).toHaveCount(0);
 await navigation.getByRole('button',{name:'Usage Limit',exact:true}).click();const bathroomMode=page.getByRole('radio',{name:/Bathroom Passes/}),weeklyMode=page.getByRole('radio',{name:/Weekly Bathroom Time/});await expect(bathroomMode).toBeChecked();await expect(weeklyMode).not.toBeChecked();await expect(page.getByRole('heading',{name:'Bathroom Passes'})).toBeVisible();await expect(page.getByLabel('Warning Threshold (minutes)')).toBeVisible();await expect(page.getByLabel('Over the Limit Threshold (minutes)')).toBeVisible();await expect(page.getByLabel('Weekly allowance (minutes)')).toHaveCount(0);const bathroomAdvanced=page.locator('details.bathroom-pass-advanced');await expect(bathroomAdvanced).not.toHaveAttribute('open','');await expect(page.getByRole('heading',{name:'Automatic Pass Suspensions'})).not.toBeVisible();await bathroomAdvanced.getByText('Advanced',{exact:true}).press('Enter');await expect(page.getByRole('heading',{name:'Automatic Pass Suspensions'})).toBeVisible();await page.getByRole('combobox',{name:'Bathroom Passes'}).selectOption('2');await expect(page.getByText('Bathroom Passes saved automatically.')).toBeVisible();await weeklyMode.check();await expect(page.getByText('Weekly Bathroom Time selected. Only this usage limit is active.')).toBeVisible();await expect(weeklyMode).toBeChecked();await expect(bathroomMode).not.toBeChecked();await expect(page.getByRole('heading',{name:'Bathroom Passes'})).toHaveCount(0);await expect(page.getByLabel('Weekly allowance (minutes)')).toBeVisible();await expect(page.getByLabel('Weekly reset day')).toBeVisible();await expect(page.getByLabel('Warn student when remaining time is at or below (minutes)')).toHaveValue('5');const weeklyDetails=page.locator('details.weekly-time-advanced');await expect(weeklyDetails).not.toHaveAttribute('open','');await weeklyDetails.getByText('Advanced',{exact:true}).press('Enter');await expect(page.getByLabel('Automatically suspend pass if student exceeds weekly limit')).toBeVisible();await expect(page.getByLabel('Minutes over before suspension')).toBeVisible();await expect(page.getByLabel('Suspension duration (days)')).toBeVisible();await page.reload();await expect(page.getByText('Ready for class')).toBeVisible();await page.getByRole('button',{name:'Open teacher dashboard'}).click();await page.getByLabel('Teacher PIN').fill('2468');await page.getByRole('button',{name:'Continue'}).click();await expect(page.getByText('Teacher dashboard')).toBeVisible();await navigation.getByRole('button',{name:'Usage Limit',exact:true}).click();await expect(page.getByRole('radio',{name:/Weekly Bathroom Time/})).toBeChecked();
 await navigation.getByRole('button',{name:'Roster',exact:true}).click();const bannedRow=page.locator('.adminrow').filter({hasText:'Fictional Student Two'});await bannedRow.getByRole('button',{name:'Ban',exact:true}).click();await expect(bannedRow).toContainText('Banned');
 await navigation.getByRole('button',{name:'Pass Suspension',exact:true}).click();await expect(page.getByRole('heading',{name:'Temporary Suspensions'})).toBeVisible();const orderedSections=await page.locator('section.manual-suspension-settings, section.probation-list').evaluateAll(elements=>elements.map(element=>element.classList.contains('manual-suspension-settings')?'temporary':'list'));expect(orderedSections).toEqual(['temporary','list']);await expect(page.getByRole('heading',{name:'Automatic Pass Suspensions'})).toHaveCount(0);await expect(page.locator('details.pass-suspension-advanced')).toHaveCount(0);await expect(page.locator('main.teacher')).not.toContainText(/manual/i);const temporary=page.locator('.manual-suspension-settings');await temporary.getByLabel('Select student').selectOption({label:'Fictional Student Two — ID ending in 1937'});await temporary.getByRole('button',{name:'Apply Temporary Suspension'}).click();const dialog=page.getByRole('dialog');await expect(dialog).toContainText('Any permanent ban on this student will be removed.');await dialog.getByLabel('Confirm teacher PIN').fill('2468');await dialog.getByRole('button',{name:'Confirm temporary suspension'}).click();let suspendedRow=page.locator('.probation-row').filter({hasText:'Fictional Student Two'});await expect(suspendedRow).toContainText('Temporary suspension');await expect(suspendedRow).not.toContainText('Permanent manual ban');
 await page.reload();await page.getByRole('button',{name:'Open teacher dashboard'}).click();await page.getByLabel('Teacher PIN').fill('2468');await page.getByRole('button',{name:'Continue'}).click();await page.getByRole('button',{name:'Pass Suspension',exact:true}).click();suspendedRow=page.locator('.probation-row').filter({hasText:'Fictional Student Two'});await expect(suspendedRow).toContainText('Temporary suspension');await expect(suspendedRow).not.toContainText('Permanent manual ban');await page.getByRole('navigation').getByRole('button',{name:'Return to student mode'}).click();await page.getByRole('button',{name:'Start Bathroom Kiosk'}).click();await keypad(page,'001482');await expect(page.getByRole('button',{name:/water/i})).toHaveCount(0);await page.getByRole('button',{name:'Add my name for the bathroom'}).click();await expect(page.getByRole('heading',{name:'Fictional Student One'})).toBeVisible();await page.getByRole('button',{name:"I'm ready to use the bathroom"}).click();await expect(page.getByText('In bathroom')).toBeVisible();await page.getByRole('button',{name:"I'm back"}).click();await expect(page.getByText('The bathroom line is currently empty.')).toBeVisible();
});

test('history deletion, factory reset, and setup-screen backup recovery work',async({page},testInfo)=>{
 await setup(page);await openTeacher(page);await page.getByRole('button',{name:'Settings'}).click();
 await page.getByRole('button',{name:'Export Encrypted Full Backup'}).click();await page.getByLabel('Backup password',{exact:true}).fill('correct horse battery');await page.getByLabel('Confirm backup password').fill('correct horse battery');const recoveryDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Encrypt and Download'}).click();const recovery=await recoveryDownload;const recoveryPath=testInfo.outputPath('factory-reset-recovery.json');await recovery.saveAs(recoveryPath);
 await page.evaluate(async()=>{const request=indexedDB.open('ClassroomBathroomQueue');const database=await new Promise<IDBDatabase>((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});await new Promise<void>((resolve,reject)=>{const tx=database.transaction('sessions','readwrite');tx.objectStore('sessions').put({id:'test-session',studentId:'missing',studentName:'Fictional Student',studentIdSnapshot:'000001',queuedAt:new Date().toISOString(),startedAt:new Date().toISOString(),endedAt:new Date().toISOString(),durationSeconds:1,durationFormatted:'0:01',reachedWarning:false,overLimit:false,status:'completed'});tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});database.close()});
 await page.getByText('Advanced Data Tools').click();await page.getByRole('button',{name:'Delete Bathroom History'}).click();await expect(page.getByRole('dialog')).toContainText('Delete Bathroom History');await page.getByLabel('Confirm teacher PIN').fill('1111');await page.getByRole('button',{name:'Delete History Permanently'}).click();await expect(page.getByText('Incorrect PIN.')).toBeVisible();await page.getByLabel('Confirm teacher PIN').fill('2468');await page.getByRole('button',{name:'Delete History Permanently'}).click();await expect(page.getByText('Bathroom history deleted.')).toBeVisible();expect(await page.evaluate(async()=>{const r=indexedDB.open('ClassroomBathroomQueue');const d=await new Promise<IDBDatabase>((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});return await new Promise<number>((resolve,reject)=>{const tx=d.transaction('sessions'),q=tx.objectStore('sessions').count();q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error)})})).toBe(0);
 await page.getByRole('button',{name:'Factory Reset',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('Factory Reset');await page.getByLabel('Confirm teacher PIN').fill('2468');await page.getByLabel('I understand that all local app data will be erased.').check();await page.getByRole('button',{name:'Factory Reset Permanently'}).click();await expect(page.getByText('Create teacher PIN')).toBeVisible();const resetPolicies=await page.evaluate(async()=>{const request=indexedDB.open('ClassroomBathroomQueue'),database=await new Promise<IDBDatabase>((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});return await new Promise<any>((resolve,reject)=>{const tx=database.transaction('settings'),get=tx.objectStore('settings').get('settings');get.onsuccess=()=>resolve({probation:get.result.probationPolicy,weekly:get.result.weeklyTimePolicy});get.onerror=()=>reject(get.error)})});expect(resetPolicies.probation).toMatchObject({warningsEnabled:false,automaticSuspensionsEnabled:false});expect(resetPolicies.weekly).toMatchObject({enabled:false,automaticSuspensionEnabled:false,allowanceMinutes:20});await page.getByLabel('Teacher PIN',{exact:true}).fill('8642');await page.getByLabel('Confirm PIN').fill('8642');await page.getByRole('button',{name:'Continue',exact:true}).click();await expect(page.getByRole('heading',{name:'Choose your teacher dashboard shortcut'})).toBeVisible();await page.getByLabel('Open teacher dashboard').selectOption('Ctrl+Shift+9');await page.getByRole('button',{name:'Save Shortcut and Continue'}).click();await page.locator('input[type=file][accept*="json"]').setInputFiles(recoveryPath);await expect(page.getByText('Valid encrypted backup ready')).toBeVisible();await page.getByLabel('Backup password').fill('correct horse battery');await page.getByRole('button',{name:'Confirm Restore Full Backup'}).click();await expect(page.getByText('Ready for class')).toBeVisible();await page.keyboard.press('Control+Shift+5');await expect(page.getByRole('dialog')).toHaveCount(0);await page.keyboard.press('Control+Shift+9');await page.getByLabel('Teacher PIN').fill('8642');await page.getByRole('button',{name:'Continue'}).click();await page.getByRole('button',{name:'Roster',exact:true}).click();await expect(page.getByText('Fictional Student One')).toBeVisible();
});

test('Aeries class associations, hidden schedule controls, and local-only operation',async({page})=>{
 await page.addInitScript(()=>{let fullscreen=false;Object.defineProperty(document,'fullscreenElement',{configurable:true,get:()=>fullscreen?document.documentElement:null});Element.prototype.requestFullscreen=async()=>{fullscreen=true;document.dispatchEvent(new Event('fullscreenchange'))};document.exitFullscreen=async()=>{fullscreen=false;document.dispatchEvent(new Event('fullscreenchange'))}});
 const remoteRequests:string[]=[];
 page.on('request',request=>{const url=new URL(request.url());if(!['127.0.0.1','localhost'].includes(url.hostname))remoteRequests.push(request.url())});
 await setup(page);
 await openTeacher(page);
 await page.getByRole('button',{name:'Roster',exact:true}).click();
 await page.locator('input[type=file][accept*="text/plain"]').setInputFiles({name:'aeries-roster.txt',mimeType:'text/plain',buffer:Buffer.from(aeriesFixture)});
 await page.getByRole('button',{name:'Import selected students'}).click();
 await page.getByRole('button',{name:'Settings'}).click();
 await expect(page.getByRole('heading',{name:'Switch Class / Period'})).not.toBeVisible();
 await expect(page.getByRole('heading',{name:'Bell Schedule'})).not.toBeVisible();
 const stored=await page.evaluate(async()=>{const request=indexedDB.open('ClassroomBathroomQueue');const database=await new Promise<IDBDatabase>((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});const read=(store:string)=>new Promise<any[]>((resolve,reject)=>{const tx=database.transaction(store),get=tx.objectStore(store).getAll();get.onsuccess=()=>resolve(get.result);get.onerror=()=>reject(get.error)});return{classes:await read('classes'),enrollments:await read('enrollments'),settings:(await read('settings'))[0]}});
 expect(stored.classes).toHaveLength(2);
 expect(stored.enrollments).toHaveLength(2);
 expect(remoteRequests).toEqual([]);
 await page.getByRole('navigation').getByRole('button',{name:'Return to student mode'}).click();await page.getByRole('button',{name:'Start Bathroom Kiosk'}).click();await keypad(page,'170000');await expect(page.getByRole('heading',{name:'Thomas L Almond'})).toBeVisible();
});

test('Ctrl+Shift+6 clears only waiting students and Undo restores exact queue state',async({page})=>{
 await page.addInitScript(()=>{let fullscreen=false;Object.defineProperty(document,'fullscreenElement',{configurable:true,get:()=>fullscreen?document.documentElement:null});Element.prototype.requestFullscreen=async()=>{fullscreen=true;document.dispatchEvent(new Event('fullscreenchange'))};document.exitFullscreen=async()=>{fullscreen=false;document.dispatchEvent(new Event('fullscreenchange'))}});
 await setup(page);
 await page.getByRole('button',{name:'Start Bathroom Kiosk'}).click();
 await keypad(page,'001482');await page.getByRole('button',{name:'Add my name for the bathroom'}).click();
 await page.getByRole('button',{name:"I'm ready to use the bathroom"}).click();
 await keypad(page,'001937');await page.getByRole('button',{name:'Add my name for the bathroom'}).click();
 const before=await page.evaluate(async()=>{const request=indexedDB.open('ClassroomBathroomQueue'),database=await new Promise<IDBDatabase>((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});return await new Promise<any[]>((resolve,reject)=>{const tx=database.transaction('queue'),get=tx.objectStore('queue').getAll();get.onsuccess=()=>resolve(get.result);get.onerror=()=>reject(get.error)})});
 await page.keyboard.press('Control+Shift+6');
 await expect(page.getByText('1 waiting student removed.')).toBeVisible();
 await expect(page.getByRole('heading',{name:'Fictional Student One'})).toBeVisible();
 await expect(page.getByText('Fictional Student Two')).not.toBeVisible();
 await page.getByRole('button',{name:'Undo'}).click();
 await expect(page.getByText('Fictional Student Two')).toBeVisible();
 const after=await page.evaluate(async()=>{const request=indexedDB.open('ClassroomBathroomQueue'),database=await new Promise<IDBDatabase>((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});return await new Promise<any[]>((resolve,reject)=>{const tx=database.transaction('queue'),get=tx.objectStore('queue').getAll();get.onsuccess=()=>resolve(get.result);get.onerror=()=>reject(get.error)})});
 expect(after.sort((a,b)=>a.queuedAt.localeCompare(b.queuedAt))).toEqual(before.sort((a,b)=>a.queuedAt.localeCompare(b.queuedAt)));
});

test('teacher schedule controls are hidden while their saved data remains intact',async({page})=>{
 await setup(page);await openTeacher(page);await page.getByRole('button',{name:'Roster',exact:true}).click();await page.locator('input[type=file][accept*="text/plain"]').setInputFiles({name:'aeries-roster.txt',mimeType:'text/plain',buffer:Buffer.from(aeriesFixture)});await page.getByRole('button',{name:'Import selected students'}).click();await page.getByRole('button',{name:'Settings'}).click();
 await expect(page.getByRole('heading',{name:'Switch Class / Period'})).not.toBeVisible();
 await expect(page.getByRole('heading',{name:'Bell Schedule'})).not.toBeVisible();
 const schedules=await page.evaluate(async()=>{const request=indexedDB.open('ClassroomBathroomQueue'),database=await new Promise<IDBDatabase>((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});return await new Promise<any[]>((resolve,reject)=>{const tx=database.transaction('bellSchedules'),get=tx.objectStore('bellSchedules').getAll();get.onsuccess=()=>resolve(get.result);get.onerror=()=>reject(get.error)})});
 expect(schedules.length).toBeGreaterThan(0);
});

test('teacher can customize both kiosk keyboard shortcuts',async({page})=>{
 await page.addInitScript(()=>{let fullscreen=false;Object.defineProperty(document,'fullscreenElement',{configurable:true,get:()=>fullscreen?document.documentElement:null});Element.prototype.requestFullscreen=async()=>{fullscreen=true;document.dispatchEvent(new Event('fullscreenchange'))};document.exitFullscreen=async()=>{fullscreen=false;document.dispatchEvent(new Event('fullscreenchange'))}});
 await setup(page);await openTeacher(page);await page.getByRole('button',{name:'Settings'}).click();await page.getByLabel('Open teacher dashboard').selectOption('Ctrl+Shift+9');await page.getByLabel('Clear waiting queue').selectOption('Ctrl+Shift+7');await page.getByRole('button',{name:'Save keyboard shortcuts'}).click();await expect(page.getByText('Keyboard shortcuts saved.')).toBeVisible();await page.getByRole('navigation').getByRole('button',{name:'Return to student mode'}).click();await page.getByRole('button',{name:'Start Bathroom Kiosk'}).click();await keypad(page,'001482');await page.getByRole('button',{name:'Add my name for the bathroom'}).click();await page.keyboard.press('Control+Shift+6');await expect(page.getByRole('heading',{name:'Fictional Student One'})).toBeVisible();await page.keyboard.press('Control+Shift+7');await expect(page.getByText('1 waiting student removed.')).toBeVisible();await page.keyboard.press('Control+Shift+9');await expect(page.getByRole('dialog').getByRole('heading',{name:'Teacher PIN'})).toBeVisible();
});

test('an existing schema-v3 installation migrates in place without exposing roster names during lookup',async({page,context})=>{
 await page.goto('/',{waitUntil:'domcontentloaded'});await expect(page.getByRole('heading',{name:'Create teacher PIN'})).toBeVisible();
 await page.evaluate(async()=>{
  const request=indexedDB.open('ClassroomBathroomQueue'),database=await new Promise<IDBDatabase>((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)}),encoded=new TextEncoder().encode('legacy-salt:2468'),digest=await crypto.subtle.digest('SHA-256',encoded),pinHash=Array.from(new Uint8Array(digest),byte=>byte.toString(16).padStart(2,'0')).join(''),stamp='2026-08-30T20:00:00.000Z',startedAt='2026-08-30T20:05:00.000Z';
  await new Promise<void>((resolve,reject)=>{const names=['students','classes','enrollments','queue','queueHistory','sessions','settings','bellSchedules'],tx=database.transaction(names,'readwrite');for(const name of names)tx.objectStore(name).clear();tx.objectStore('students').put({id:'internal-one',name:'Fictional Leading Zero',studentId:'000123',createdAt:stamp,updatedAt:stamp,maxUses:2,banned:true});tx.objectStore('students').put({id:'internal-two',name:'Fictional Waiting Student',studentId:'654321',createdAt:stamp,updatedAt:stamp});tx.objectStore('classes').put({id:'class-legacy',period:'P3',courseTitle:'Fictional Civics',createdAt:stamp,updatedAt:stamp});tx.objectStore('enrollments').put({id:'enrollment-legacy',studentId:'internal-one',classId:'class-legacy',createdAt:stamp,updatedAt:stamp});tx.objectStore('queue').put({id:'active-legacy',studentId:'internal-one',queuedAt:'2026-08-30T20:01:00.000Z',startedAt,status:'active',createdAt:stamp,updatedAt:stamp});tx.objectStore('queue').put({id:'waiting-legacy',studentId:'internal-two',queuedAt:'2026-08-30T20:02:00.000Z',status:'waiting',createdAt:stamp,updatedAt:stamp});tx.objectStore('sessions').put({id:'session-legacy',studentId:'internal-one',studentName:'Fictional Leading Zero',studentIdSnapshot:'000123',queuedAt:stamp,startedAt:stamp,endedAt:stamp,durationSeconds:10,durationFormatted:'0:10',reachedWarning:false,overLimit:false,status:'completed'});tx.objectStore('bellSchedules').put({id:'custom-schedule',name:'Preserved Custom Schedule',createdAt:stamp,updatedAt:stamp,days:{}});tx.objectStore('settings').put({id:'settings',schemaVersion:3,privacyVersion:3,setupComplete:true,pinHash,pinSalt:'legacy-salt',warningSeconds:300,overLimitSeconds:420,idDisplay:'masked',globalUseLimit:4,countWaterAsBathroom:false,teacherHotkey:'Ctrl+Shift+5',clearQueueHotkey:'Ctrl+Shift+6',activeScheduleId:'custom-schedule'});tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)});database.close();
 });
 const second=await context.newPage();await Promise.all([page.reload(),second.goto('/')]);
 await expect(page.getByRole('dialog')).toContainText('Privacy update complete');await expect(second.getByRole('dialog')).toContainText('Privacy update complete');
 const migrated=await page.evaluate(async()=>{const request=indexedDB.open('ClassroomBathroomQueue'),database=await new Promise<IDBDatabase>((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)}),read=(name:string)=>new Promise<any[]>((resolve,reject)=>{const tx=database.transaction(name),get=tx.objectStore(name).getAll();get.onsuccess=()=>resolve(get.result);get.onerror=()=>reject(get.error)});return{students:await read('students'),classes:await read('classes'),enrollments:await read('enrollments'),queue:await read('queue'),sessions:await read('sessions'),settings:(await read('settings'))[0],schedules:await read('bellSchedules')}});
 expect(migrated.students.map((student:any)=>student.id).sort()).toEqual(['internal-one','internal-two']);expect(migrated.students.every((student:any)=>!('studentId'in student)&&/^[0-9a-f]{64}$/.test(student.externalIdHash))).toBe(true);expect(migrated.students.find((student:any)=>student.id==='internal-one')).toMatchObject({name:'Fictional Leading Zero',externalIdLast4:'0123',maxUses:2,banned:true});expect(migrated.classes).toHaveLength(1);expect(migrated.enrollments[0]).toMatchObject({studentId:'internal-one',classId:'class-legacy'});expect(migrated.queue.sort((a:any,b:any)=>a.queuedAt.localeCompare(b.queuedAt)).map((item:any)=>item.id)).toEqual(['active-legacy','waiting-legacy']);expect(migrated.queue.find((item:any)=>item.id==='active-legacy').startedAt).toBe('2026-08-30T20:05:00.000Z');expect(migrated.sessions[0]).not.toHaveProperty('studentIdSnapshot');expect(migrated.settings).toMatchObject({schemaVersion:4,privacyVersion:4,pinHash:migrated.settings.pinHash,pinSalt:'legacy-salt',setupComplete:true,globalUseLimit:4,privacyNoticeAcknowledged:false});expect(migrated.schedules[0].name).toBe('Preserved Custom Schedule');
 await second.close();await page.getByRole('button',{name:'Continue'}).click();const release=page.getByRole('dialog');await expect(release.getByRole('heading',{name:'New: Pass Suspension and weekly bathroom-time limits'})).toBeVisible();await release.getByRole('button',{name:'Got it'}).click();await expect(page.getByText('Ready for class')).toBeVisible();await page.getByRole('button',{name:'Start Bathroom Kiosk'}).click();await page.getByRole('button',{name:'Add/remove my name from the bathroom line'}).click();for(const digit of'00012')await page.locator('.keypad').getByRole('button',{name:digit,exact:true}).click();await expect(page.getByText('Fictional Leading Zero')).not.toBeVisible();await expect(page.getByText('Fictional Waiting Student')).not.toBeVisible();await page.getByRole('button',{name:'Find me'}).click();await expect(page.getByRole('alert')).toHaveText('Student ID not found');for(const digit of'000123')await page.locator('.keypad').getByRole('button',{name:digit,exact:true}).click();await page.getByRole('button',{name:'Find me'}).click();await expect(page.getByRole('heading',{name:'Fictional Leading Zero'})).toBeVisible();await page.getByRole('button',{name:'Back to home page'}).click();await openTeacher(page);
});
