import{atomicReplace,normalizeSettings,normalizedRetentionDays,snapshot}from'./db';
import{purgeDetailedHistory}from'./retention';
import{base64UrlToBytes,bytesToBase64Url,deriveExternalIdHash,externalIdLast4,normalizeExternalId,validLookupSecret}from'./privacy';
import type{AppData,Backup,BackupPayloadV4,EncryptedBackupV4,LegacyBackup,LegacyStudent,Session,Settings,Student}from'./types';
import{normalizeProbationPolicy,validateProbationPolicy}from'./probation';
import{normalizeWeeklyTimePolicy,validateWeeklyTimePolicy}from'./weeklyTime';

const encoder=new TextEncoder(),decoder=new TextDecoder(),ITERATIONS=310_000;
async function passwordKey(password:string,salt:Uint8Array,usage:KeyUsage[],iterations=ITERATIONS){if(password.length<10)throw new Error('Backup password must be at least 10 characters.');const material=await crypto.subtle.importKey('raw',encoder.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',hash:'SHA-256',salt,iterations},material,{name:'AES-GCM',length:256},false,usage)}
function validSuspension(student:Student){const suspension=student.passSuspension;if(student.probationExempt!==undefined&&typeof student.probationExempt!=='boolean')return false;if(student.weeklyTimeLimitMinutes!==undefined&&student.weeklyTimeLimitMinutes!==null&&(!Number.isInteger(student.weeklyTimeLimitMinutes)||student.weeklyTimeLimitMinutes<0))return false;if(student.lastAutoSuspensionTriggerKey!==undefined&&typeof student.lastAutoSuspensionTriggerKey!=='string')return false;if(student.lastWeeklyTimeSuspensionTriggerKey!==undefined&&typeof student.lastWeeklyTimeSuspensionTriggerKey!=='string')return false;if(!suspension)return true;return(suspension.kind==='automatic'||suspension.kind==='manual')&&(suspension.source===undefined||['rolling-30-day','weekly-time','manual'].includes(suspension.source))&&Number.isFinite(new Date(suspension.startedAt).getTime())&&Number.isFinite(new Date(suspension.endsAt).getTime())&&Array.isArray(suspension.reasons)&&suspension.reasons.every(reason=>typeof reason==='string')&&(suspension.triggerKey===undefined||typeof suspension.triggerKey==='string')}
function validCurrentData(data:unknown):data is AppData{const value=data as AppData,probation=normalizeProbationPolicy(value?.settings?.probationPolicy),mode=value?.settings?.usageLimitMode;if(!value||!Array.isArray(value.students)||!Array.isArray(value.classes)||!Array.isArray(value.enrollments)||!Array.isArray(value.queue)||!Array.isArray(value.queueHistory)||!Array.isArray(value.sessions)||!Array.isArray(value.bellSchedules)||value.settings?.id!=='settings'||value.settings.schemaVersion!==4||value.settings.privacyVersion!==4||(mode!==undefined&&mode!=='bathroom-passes'&&mode!=='weekly-time')||!validLookupSecret(value.settings.lookupSecret)||(value.settings.probationPolicy!==undefined&&Boolean(validateProbationPolicy(probation)))||(value.settings.weeklyTimePolicy!==undefined&&Boolean(validateWeeklyTimePolicy(normalizeWeeklyTimePolicy(value.settings.weeklyTimePolicy)))))return false;const studentIds=new Set(value.students.map(student=>student.id)),classIds=new Set(value.classes.map(item=>item.id)),hashes=new Set(value.students.map(student=>student.externalIdHash));return studentIds.size===value.students.length&&hashes.size===value.students.length&&value.students.every(student=>typeof student.id==='string'&&typeof student.name==='string'&&!('studentId'in student)&&/^[0-9a-f]{64}$/.test(student.externalIdHash)&&/^\d{1,4}$/.test(student.externalIdLast4)&&validSuspension(student))&&value.queue.every(item=>studentIds.has(item.studentId))&&value.enrollments.every(item=>studentIds.has(item.studentId)&&classIds.has(item.classId))&&value.sessions.every(session=>!('studentIdSnapshot'in session))}
export function validateBackup(value:unknown):value is Backup{const backup=value as Backup;if(backup?.format==='classroom-bathroom-queue-encrypted')return backup.backupVersion===4&&backup.schemaVersion===4&&backup.kdf?.name==='PBKDF2'&&backup.kdf.hash==='SHA-256'&&Number.isInteger(backup.kdf.iterations)&&backup.kdf.iterations>=310_000&&backup.kdf.iterations<=2_000_000&&typeof backup.kdf.salt==='string'&&backup.cipher?.name==='AES-GCM'&&typeof backup.cipher.iv==='string'&&typeof backup.ciphertext==='string'&&backup.ciphertext.length>20;if(backup?.format==='classroom-bathroom-queue')return[1,2,3].includes(backup.backupVersion)&&[1,2,3].includes(backup.schemaVersion)&&Array.isArray(backup.students)&&Array.isArray(backup.queue)&&Array.isArray(backup.sessions)&&backup.settings?.id==='settings';return false}
export async function createEncryptedBackup(password:string):Promise<EncryptedBackupV4>{await purgeDetailedHistory();const data=await snapshot(),payload:BackupPayloadV4={format:'classroom-bathroom-queue-payload',backupVersion:4,schemaVersion:4,exportedAt:new Date().toISOString(),data:{...data,settings:{...data.settings,pinHash:'',pinSalt:''}}},salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await passwordKey(password,salt,['encrypt']),ciphertext=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,encoder.encode(JSON.stringify(payload)));return{format:'classroom-bathroom-queue-encrypted',backupVersion:4,schemaVersion:4,kdf:{name:'PBKDF2',hash:'SHA-256',iterations:ITERATIONS,salt:bytesToBase64Url(salt)},cipher:{name:'AES-GCM',iv:bytesToBase64Url(iv)},ciphertext:bytesToBase64Url(new Uint8Array(ciphertext))}}
export async function decryptBackup(backup:EncryptedBackupV4,password:string){try{if(!validateBackup(backup))throw new Error();const salt=base64UrlToBytes(backup.kdf.salt),iv=base64UrlToBytes(backup.cipher.iv);if(salt.length!==16||iv.length!==12)throw new Error();const key=await passwordKey(password,salt,['decrypt'],backup.kdf.iterations),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv},key,base64UrlToBytes(backup.ciphertext)),payload=JSON.parse(decoder.decode(plain)) as BackupPayloadV4;if(payload.format!=='classroom-bathroom-queue-payload'||payload.backupVersion!==4||payload.schemaVersion!==4||!validCurrentData(payload.data))throw new Error();return payload}catch{throw new Error('Backup password is incorrect or the backup file is damaged.')}}
function validLegacy(backup:LegacyBackup){if(!backup.students.every(student=>{try{return!!student.id&&!!student.name&&normalizeExternalId(student.studentId).length>0}catch{return false}}))return false;const ids=new Set(backup.students.map(student=>student.id));return ids.size===backup.students.length&&backup.queue.every(item=>ids.has(item.studentId))&&(backup.enrollments??[]).every(item=>ids.has(item.studentId))}
function retainRecent<T extends{endedAt?:string;exitedAt?:string}>(records:T[],field:'endedAt'|'exitedAt',days:number,at=new Date()){const cutoff=at.getTime()-days*86_400_000;return records.filter(record=>{const time=new Date(record[field]??'').getTime();return!Number.isFinite(time)||time>=cutoff})}
async function convertLegacy(backup:LegacyBackup,current:Settings):Promise<AppData>{if(!validLegacy(backup)||!validLookupSecret(current.lookupSecret))throw new Error('Invalid legacy backup. Current data was not changed.');const students:Student[]=[];for(const legacy of backup.students as LegacyStudent[]){const normalized=normalizeExternalId(legacy.studentId),{studentId:_,...rest}=legacy;void _;students.push({...rest,externalIdHash:await deriveExternalIdHash(current.lookupSecret,normalized),externalIdLast4:externalIdLast4(normalized)})}if(new Set(students.map(student=>student.externalIdHash)).size!==students.length)throw new Error('Legacy backup contains duplicate student IDs. Current data was not changed.');const sessions=(backup.sessions as Array<Session&{studentIdSnapshot?:string}>).map(raw=>{const{studentIdSnapshot:_,...session}=raw;void _;return session}),historyRetentionDays=normalizedRetentionDays(current.historyRetentionDays),settings=normalizeSettings({...backup.settings,pinHash:current.pinHash,pinSalt:current.pinSalt,setupComplete:current.setupComplete||Boolean(backup.settings.setupComplete),lookupSecret:current.lookupSecret,schemaVersion:4,privacyVersion:4,privacyMigrationCompletedAt:current.privacyMigrationCompletedAt??new Date().toISOString(),privacyNoticeAcknowledged:true,historyRetentionDays} as Partial<Settings>);return{students,classes:backup.classes??[],enrollments:backup.enrollments??[],queue:backup.queue,queueHistory:retainRecent(backup.queueHistory??[],'exitedAt',historyRetentionDays),sessions:retainRecent(sessions,'endedAt',historyRetentionDays),bellSchedules:backup.bellSchedules??[],settings}}
export async function restoreAnyBackup(backup:Backup,current:Settings,password?:string){if(!validateBackup(backup))throw new Error('Invalid or unsupported backup file. Current data was not changed.');let data:AppData,legacy=false;if(backup.format==='classroom-bathroom-queue-encrypted'){if(!password)throw new Error('Enter the backup password.');data=(await decryptBackup(backup,password)).data;data={...data,settings:{...data.settings,pinHash:current.pinHash,pinSalt:current.pinSalt,setupComplete:current.setupComplete||data.settings.setupComplete,privacyNoticeAcknowledged:true,historyRetentionDays:normalizedRetentionDays(data.settings.historyRetentionDays)}}}else{legacy=true;data=await convertLegacy(backup,current)}await atomicReplace(data);await purgeDetailedHistory();return{legacy}}
