import Dexie,{type Table}from'dexie';
import type{Student,QueueEntry,QueueHistory,Session,Settings,ClassRecord,Enrollment,BellSchedule,AppData}from'./types';
import{builtInDefaultSchedule,DEFAULT_SCHEDULE_ID}from'./schedule';
import{defaultProbationPolicy,normalizeProbationPolicy}from'./probation';
import{defaultWeeklyTimePolicy,normalizeWeeklyTimePolicy}from'./weeklyTime';

export class AppDB extends Dexie{
 students!:Table<Student,string>;classes!:Table<ClassRecord,string>;enrollments!:Table<Enrollment,string>;queue!:Table<QueueEntry,string>;queueHistory!:Table<QueueHistory,string>;sessions!:Table<Session,string>;settings!:Table<Settings,string>;bellSchedules!:Table<BellSchedule,string>;
 constructor(){super('ClassroomBathroomQueue');this.version(1).stores({students:'id,&studentId,name',queue:'id,&studentId,queuedAt,status',sessions:'id,studentId,endedAt,status',settings:'id'});this.version(2).stores({students:'id,&studentId,name',classes:'id,period,courseId,sectionNumber',enrollments:'id,studentId,classId,[studentId+classId]',queue:'id,&studentId,queuedAt,status',sessions:'id,studentId,classId,endedAt,status',settings:'id'});this.version(3).stores({students:'id,&studentId,name',classes:'id,period,courseId,sectionNumber',enrollments:'id,studentId,classId,[studentId+classId]',queue:'id,&studentId,classId,queuedAt,status',queueHistory:'id,queueEntryId,studentId,classId,exitedAt,exitReason',sessions:'id,studentId,classId,endedAt,status',settings:'id',bellSchedules:'id,name'});this.version(4).stores({students:'id,&externalIdHash,name,externalIdLast4',classes:'id,period,courseId,sectionNumber',enrollments:'id,studentId,classId,[studentId+classId]',queue:'id,&studentId,classId,queuedAt,status',queueHistory:'id,queueEntryId,studentId,classId,exitedAt,exitReason',sessions:'id,studentId,classId,endedAt,status',settings:'id',bellSchedules:'id,name'})}
}
export const db=new AppDB();
export const defaults:Settings={id:'settings',warningSeconds:300,overLimitSeconds:420,pinHash:'',pinSalt:'',idDisplay:'masked',schemaVersion:4,setupComplete:false,usageLimitMode:'bathroom-passes',globalUseLimit:0,countWaterAsBathroom:false,teacherHotkey:'Ctrl+Shift+5',clearQueueHotkey:'Ctrl+Shift+6',activeScheduleId:DEFAULT_SCHEDULE_ID,lookupSecret:'',privacyVersion:4,privacyNoticeAcknowledged:true,historyRetentionDays:30,probationPolicy:defaultProbationPolicy,weeklyTimePolicy:defaultWeeklyTimePolicy};
export function normalizedRetentionDays(value:unknown){const days=typeof value==='number'&&Number.isFinite(value)?Math.floor(value):30;return Math.max(1,Math.min(30,days))}
export function normalizeSettings(value?:Partial<Settings>):Settings{const weeklyTimePolicy=normalizeWeeklyTimePolicy(value?.weeklyTimePolicy),usageLimitMode=value?.usageLimitMode==='bathroom-passes'||value?.usageLimitMode==='weekly-time'?value.usageLimitMode:weeklyTimePolicy.enabled?'weekly-time':'bathroom-passes';return{...defaults,...value,usageLimitMode,probationPolicy:normalizeProbationPolicy(value?.probationPolicy),weeklyTimePolicy:usageLimitMode==='weekly-time'?{...weeklyTimePolicy,enabled:true}:weeklyTimePolicy,schemaVersion:4,privacyVersion:4,historyRetentionDays:normalizedRetentionDays(value?.historyRetentionDays)}}
export async function getSettings(){return normalizeSettings(await db.settings.get('settings'))}
export async function ensureDefaultSchedule(){if(!await db.bellSchedules.count())await db.bellSchedules.put(builtInDefaultSchedule())}
export async function snapshot():Promise<AppData>{await ensureDefaultSchedule();return{students:await db.students.toArray(),classes:await db.classes.toArray(),enrollments:await db.enrollments.toArray(),queue:(await db.queue.toArray()).sort((a,b)=>a.queuedAt.localeCompare(b.queuedAt)),queueHistory:await db.queueHistory.toArray(),sessions:await db.sessions.toArray(),bellSchedules:await db.bellSchedules.toArray(),settings:await getSettings()}}
export async function atomicReplace(data:{students:Student[];classes?:ClassRecord[];enrollments?:Enrollment[];queue:QueueEntry[];queueHistory?:QueueHistory[];sessions:Session[];bellSchedules?:BellSchedule[];settings:Settings}){await db.transaction('rw',[db.students,db.classes,db.enrollments,db.queue,db.queueHistory,db.sessions,db.bellSchedules,db.settings],async()=>{await Promise.all([db.students.clear(),db.classes.clear(),db.enrollments.clear(),db.queue.clear(),db.queueHistory.clear(),db.sessions.clear(),db.bellSchedules.clear(),db.settings.clear()]);await db.students.bulkAdd(data.students);await db.classes.bulkAdd(data.classes??[]);await db.enrollments.bulkAdd(data.enrollments??[]);await db.queue.bulkAdd(data.queue);await db.queueHistory.bulkAdd(data.queueHistory??[]);await db.sessions.bulkAdd(data.sessions);await db.bellSchedules.bulkAdd(data.bellSchedules?.length?data.bellSchedules:[builtInDefaultSchedule()]);await db.settings.put(normalizeSettings(data.settings))})}
