import Dexie,{type Table}from'dexie';
import type{Student,QueueEntry,QueueHistory,Session,Settings,ClassRecord,Enrollment,BellSchedule}from'./types';
import{builtInDefaultSchedule,DEFAULT_SCHEDULE_ID}from'./schedule';

export class AppDB extends Dexie{
 students!:Table<Student,string>;classes!:Table<ClassRecord,string>;enrollments!:Table<Enrollment,string>;queue!:Table<QueueEntry,string>;queueHistory!:Table<QueueHistory,string>;sessions!:Table<Session,string>;settings!:Table<Settings,string>;bellSchedules!:Table<BellSchedule,string>;
 constructor(){super('ClassroomBathroomQueue');this.version(1).stores({students:'id,&studentId,name',queue:'id,&studentId,queuedAt,status',sessions:'id,studentId,endedAt,status',settings:'id'});this.version(2).stores({students:'id,&studentId,name',classes:'id,period,courseId,sectionNumber',enrollments:'id,studentId,classId,[studentId+classId]',queue:'id,&studentId,queuedAt,status',sessions:'id,studentId,classId,endedAt,status',settings:'id'});this.version(3).stores({students:'id,&studentId,name',classes:'id,period,courseId,sectionNumber',enrollments:'id,studentId,classId,[studentId+classId]',queue:'id,&studentId,classId,queuedAt,status',queueHistory:'id,queueEntryId,studentId,classId,exitedAt,exitReason',sessions:'id,studentId,classId,endedAt,status',settings:'id',bellSchedules:'id,name'})}
}
export const db=new AppDB();
export const defaults:Settings={id:'settings',warningSeconds:300,overLimitSeconds:420,pinHash:'',pinSalt:'',idDisplay:'masked',schemaVersion:3,setupComplete:false,globalUseLimit:0,countWaterAsBathroom:false,activeScheduleId:DEFAULT_SCHEDULE_ID};
export async function getSettings(){return{...defaults,...(await db.settings.get('settings'))}}
export async function ensureDefaultSchedule(){if(!await db.bellSchedules.count())await db.bellSchedules.put(builtInDefaultSchedule())}
export async function snapshot(){await ensureDefaultSchedule();return{students:await db.students.toArray(),classes:await db.classes.toArray(),enrollments:await db.enrollments.toArray(),queue:(await db.queue.toArray()).sort((a,b)=>a.queuedAt.localeCompare(b.queuedAt)),queueHistory:await db.queueHistory.toArray(),sessions:await db.sessions.toArray(),bellSchedules:await db.bellSchedules.toArray(),settings:await getSettings()}}
export async function atomicReplace(data:{students:Student[];classes?:ClassRecord[];enrollments?:Enrollment[];queue:QueueEntry[];queueHistory?:QueueHistory[];sessions:Session[];bellSchedules?:BellSchedule[];settings:Settings}){await db.transaction('rw',[db.students,db.classes,db.enrollments,db.queue,db.queueHistory,db.sessions,db.bellSchedules,db.settings],async()=>{await Promise.all([db.students.clear(),db.classes.clear(),db.enrollments.clear(),db.queue.clear(),db.queueHistory.clear(),db.sessions.clear(),db.bellSchedules.clear(),db.settings.clear()]);await db.students.bulkAdd(data.students);await db.classes.bulkAdd(data.classes??[]);await db.enrollments.bulkAdd(data.enrollments??[]);await db.queue.bulkAdd(data.queue);await db.queueHistory.bulkAdd(data.queueHistory??[]);await db.sessions.bulkAdd(data.sessions);await db.bellSchedules.bulkAdd(data.bellSchedules?.length?data.bellSchedules:[builtInDefaultSchedule()]);await db.settings.put({...defaults,...data.settings,schemaVersion:3})})}
