import Papa from 'papaparse'; import {db,getSettings,snapshot,atomicReplace,defaults} from './db'; import type {Student,QueueEntry,Session,Backup,Settings,PassType} from './types';
export const uid=()=>crypto.randomUUID(); export const now=()=>new Date().toISOString();
export function formatDuration(total:number){total=Math.max(0,Math.floor(total));const h=Math.floor(total/3600),m=Math.floor(total%3600/60),s=total%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${m}:${String(s).padStart(2,'0')}`}
export function elapsed(start?:string){return start?Math.max(0,Math.floor((Date.now()-new Date(start).getTime())/1000)):0}
export function timerLevel(sec:number,s:Settings){return sec>=s.overLimitSeconds?'over':sec>=s.warningSeconds?'warning':'neutral'}
export async function hashPin(pin:string,salt:string){const bytes=new TextEncoder().encode(`${salt}:${pin}`);const hash=await crypto.subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(hash),b=>b.toString(16).padStart(2,'0')).join('')}
export async function makePin(pin:string){const salt=uid();return{pinSalt:salt,pinHash:await hashPin(pin,salt)}}
export async function verifyPin(pin:string,s:Settings){return !!s.pinHash&&(await hashPin(pin,s.pinSalt))===s.pinHash}
export function validateStudent(name:string,id:string,students:Student[],ignore?:string){const n=name.trim(),sid=id.trim();if(!n)return'Name is required.';if(!sid)return'Student ID is required.';if(!/^\d+$/.test(sid))return'Student ID must contain digits only.';if(students.some(x=>x.studentId===sid&&x.id!==ignore))return'Student ID must be unique.';return''}
export function countedSessions(sessions:Session[],settings:Settings){return sessions.filter(x=>x.status==='completed'&&(settings.countWaterAsBathroom||(x.passType??'bathroom')==='bathroom'))}
export async function useEligibility(student:Student,settings:Settings,sessions:Session[]){if(student.banned)return{allowed:false,reason:'Bathroom and water passes are not available for this student.'};const limit=student.maxUses==null?settings.globalUseLimit:student.maxUses;if(limit>0){const used=countedSessions(sessions,settings).filter(x=>x.studentId===student.id).length;if(used>=limit)return{allowed:false,reason:`You have reached your limit of ${limit} use${limit===1?'':'s'}.`}}return{allowed:true,reason:''}}
export async function addToQueue(studentId:string,passType:PassType='bathroom'){return db.transaction('rw',db.queue,db.students,db.sessions,db.settings,async()=>{if(await db.queue.where('studentId').equals(studentId).first())throw new Error('Student is already in line.');const student=await db.students.get(studentId);if(!student)throw new Error('Student was not found.');const settings=await getSettings(),eligibility=await useEligibility(student,settings,await db.sessions.toArray());if(!eligibility.allowed)throw new Error(eligibility.reason);const item:QueueEntry={id:uid(),studentId,queuedAt:now(),status:'waiting',passType};await db.queue.add(item);return item})}
export async function startTimer(entryId:string){return db.transaction('rw',db.queue,async()=>{const q=(await db.queue.toArray()).sort((a,b)=>a.queuedAt.localeCompare(b.queuedAt));if(!q.length||q[0].id!==entryId)throw new Error('Only the first student may start the timer.');if(q.some(x=>x.status==='active'))throw new Error('A timer is already active.');await db.queue.update(entryId,{status:'active',startedAt:now()})})}
export async function finishActive(status:Session['status']='completed'){const settings=await getSettings();return db.transaction('rw',db.queue,db.students,db.sessions,async()=>{const active=await db.queue.where('status').equals('active').first();if(!active||!active.startedAt)throw new Error('No active bathroom session.');const student=await db.students.get(active.studentId);const end=now(),seconds=Math.max(0,Math.floor((new Date(end).getTime()-new Date(active.startedAt).getTime())/1000)),passType=active.passType??'bathroom',warningAt=passType==='water'?90:settings.warningSeconds,overAt=passType==='water'?90:settings.overLimitSeconds;const item:Session={id:uid(),studentId:active.studentId,studentName:student?.name??'Deleted student',studentIdSnapshot:student?.studentId??'',queuedAt:active.queuedAt,startedAt:active.startedAt,endedAt:end,durationSeconds:seconds,durationFormatted:formatDuration(seconds),reachedWarning:seconds>=warningAt,overLimit:seconds>=overAt,status,passType,classId:settings.currentClassId,createdAt:end,updatedAt:end};await db.sessions.add(item);await db.queue.delete(active.id);return item})}
export function studentStats(students:Student[],sessions:Session[],settings:Settings={...({countWaterAsBathroom:false} as Settings)}){return students.map(student=>{const completed=countedSessions(sessions,settings).filter(x=>x.studentId===student.id),recent=[...completed].sort((a,b)=>b.endedAt.localeCompare(a.endedAt))[0],over=completed.filter(x=>x.overLimit).length;return{student,total:completed.length,over,percent:completed.length?Math.round(over/completed.length*100):0,average:completed.length?Math.round(completed.reduce((a,x)=>a+x.durationSeconds,0)/completed.length):0,recent:recent?.endedAt}})}
export function parseRosterCsv(text:string,existing:Student[]){const parsed=Papa.parse<Record<string,string>>(text,{header:true,skipEmptyLines:true});const seen=new Set<string>();const rows=(parsed.data||[]).map((r,i)=>{const name=(r.name??'').trim(),studentId=(r.studentId??'').trim();let error='';if(!name)error='Missing name';else if(!studentId)error='Missing student ID';else if(!/^\d+$/.test(studentId))error='Student ID must contain digits only';else if(seen.has(studentId))error='Duplicate ID in file';seen.add(studentId);return{row:i+2,name,studentId,error,conflict:existing.some(s=>s.studentId===studentId)}});if(parsed.errors.length)rows.push({row:0,name:'',studentId:'',error:'Invalid CSV',conflict:false});return rows}
const esc=(v:unknown)=>`"${String(v??'').replaceAll('"','""')}"`; export const rosterCsv=(s:Student[])=>['name,studentId',...s.map(x=>`${esc(x.name)},${esc(x.studentId)}`)].join('\r\n');
export const historyCsv=(s:Session[])=>['studentName,studentId,queuedAt,startedAt,endedAt,durationSeconds,durationFormatted,reachedWarning,overLimit,status',...[...s].sort((a,b)=>b.endedAt.localeCompare(a.endedAt)).map(x=>[x.studentName,x.studentIdSnapshot,x.queuedAt,x.startedAt,x.endedAt,x.durationSeconds,x.durationFormatted,x.reachedWarning,x.overLimit,x.status].map(esc).join(','))].join('\r\n');
export async function createBackup():Promise<Backup>{const x=await snapshot();const {pinHash:_,pinSalt:__,...safe}=x.settings;void _;void __;return{format:'classroom-bathroom-queue',backupVersion:2,schemaVersion:2,exportedAt:now(),students:x.students,classes:x.classes,enrollments:x.enrollments,queue:x.queue,sessions:x.sessions,settings:{...safe,pinProtected:true}}}
export function validateBackup(x:any):x is Backup{return x?.format==='classroom-bathroom-queue'&&[1,2].includes(x.backupVersion)&&[1,2].includes(x.schemaVersion)&&Array.isArray(x.students)&&Array.isArray(x.queue)&&Array.isArray(x.sessions)&&x.settings?.id==='settings'}
export async function restoreBackup(b:Backup,current:Settings){if(!validateBackup(b))throw new Error('Invalid or unsupported backup.');await atomicReplace({students:b.students,classes:b.classes??[],enrollments:b.enrollments??[],queue:b.queue,sessions:b.sessions,settings:{...defaults,...b.settings,pinHash:current.pinHash,pinSalt:current.pinSalt} as Settings})}
export function download(name:string,data:string,type:string){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
