import Papa from'papaparse';import{db,defaults,getSettings}from'./db';import type{Student,QueueEntry,Session,Settings,PassType,QueueHistory}from'./types';import{normalizeExternalId}from'./privacy';import{purgeDetailedHistory}from'./retention';
import{activePassSuspension,reconcileStudentProbation}from'./probation';
import{assessWeeklyTime,reconcileStudentWeeklyTime}from'./weeklyTime';
export{validateBackup,createEncryptedBackup,restoreAnyBackup,decryptBackup}from'./backup';
export const uid=()=>crypto.randomUUID();export const now=()=>new Date().toISOString();
export function formatDuration(total:number){total=Math.max(0,Math.floor(total));const h=Math.floor(total/3600),m=Math.floor(total%3600/60),s=total%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${m}:${String(s).padStart(2,'0')}`}
export function elapsed(start?:string){return start?Math.max(0,Math.floor((Date.now()-new Date(start).getTime())/1000)):0}
export function timerLevel(sec:number,s:Settings){return sec>=s.overLimitSeconds?'over':sec>=s.warningSeconds?'warning':'neutral'}
export async function hashPin(pin:string,salt:string){const bytes=new TextEncoder().encode(`${salt}:${pin}`),hash=await crypto.subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(hash),b=>b.toString(16).padStart(2,'0')).join('')}
export async function makePin(pin:string){const salt=uid();return{pinSalt:salt,pinHash:await hashPin(pin,salt)}}
export async function verifyPin(pin:string,s:Settings){return!!s.pinHash&&(await hashPin(pin,s.pinSalt))===s.pinHash}
export function validateStudent(name:string,id:string,_students:Student[]=[],_ignore?:string){void _students;void _ignore;if(!name.trim())return'Name is required.';try{normalizeExternalId(id)}catch(error){return(error as Error).message}return''}
export const HOTKEY_OPTIONS=['Ctrl+Shift+5','Ctrl+Shift+6','Ctrl+Shift+7','Ctrl+Shift+8','Ctrl+Shift+9','Ctrl+Alt+5','Ctrl+Alt+6','Ctrl+Alt+7','Ctrl+Alt+8','Ctrl+Alt+9','Alt+Shift+5','Alt+Shift+6','Alt+Shift+7','Alt+Shift+8','Alt+Shift+9'] as const;
export function validateHotkeyPair(teacherHotkey:string,clearQueueHotkey:string){return teacherHotkey===clearQueueHotkey?'The teacher dashboard shortcut must be different from the clear-queue shortcut.':''}
export function resolveTeacherHotkeyAfterRestore(selectedHotkey:string,restoredTeacherHotkey:string,restoredClearQueueHotkey:string){if(!validateHotkeyPair(selectedHotkey,restoredClearQueueHotkey))return selectedHotkey;if(HOTKEY_OPTIONS.includes(restoredTeacherHotkey as typeof HOTKEY_OPTIONS[number])&&!validateHotkeyPair(restoredTeacherHotkey,restoredClearQueueHotkey))return restoredTeacherHotkey;return HOTKEY_OPTIONS.find(value=>!validateHotkeyPair(value,restoredClearQueueHotkey))??defaults.teacherHotkey}
export type StudentIdKeyboardAction={type:'digit';digit:string}|{type:'backspace'|'submit'|'clear'|'none'};
export function studentIdKeyboardAction(event:Pick<KeyboardEvent,'ctrlKey'|'altKey'|'metaKey'|'code'|'key'>):StudentIdKeyboardAction{if(event.ctrlKey||event.altKey||event.metaKey)return{type:'none'};const digit=/^(?:Digit|Numpad)(\d)$/.exec(event.code)?.[1];if(digit)return{type:'digit',digit};if(event.key==='Backspace')return{type:'backspace'};if(event.key==='Enter')return{type:'submit'};if(event.key==='Escape')return{type:'clear'};return{type:'none'}}
export function countedSessions(sessions:Session[],settings:Settings){return sessions.filter(x=>x.status==='completed'&&(settings.countWaterAsBathroom||(x.passType??'bathroom')==='bathroom'))}
export async function useEligibility(student:Student,settings:Settings,sessions:Session[],at=new Date(),passType:PassType='bathroom'){if(student.banned)return{allowed:false,reason:'Bathroom passes are not available for this student.'};const suspension=activePassSuspension(student,settings,at);if(suspension)return{allowed:false,reason:`Bathroom-pass access in this app is temporarily suspended until ${new Date(suspension.endsAt).toLocaleString()}. Speak with your teacher if this is an emergency or you have an accommodation.`};if(settings.usageLimitMode==='bathroom-passes'){const limit=student.maxUses==null?settings.globalUseLimit:student.maxUses;if(limit>0){const used=countedSessions(sessions,settings).filter(x=>x.studentId===student.id).length;if(used>=limit)return{allowed:false,reason:`You have reached your limit of ${limit} use${limit===1?'':'s'}.`}}}if(passType==='bathroom'||settings.countWaterAsBathroom){const weekly=assessWeeklyTime(student,sessions,settings,at);if(weekly.blocked)return{allowed:false,reason:`You have used your weekly bathroom-time allowance. It resets ${weekly.weekEnd.toLocaleString()}. Speak with your teacher if this is an emergency or you have an accommodation.`}}return{allowed:true,reason:''}}
export function hotkeyMatches(event:Pick<KeyboardEvent,'ctrlKey'|'shiftKey'|'altKey'|'metaKey'|'key'|'code'>,hotkey:string){const parts=hotkey.toLowerCase().split('+'),key=parts.at(-1)??'',physicalKey=/^\d$/.test(key)?`digit${key}`:key;return event.ctrlKey===parts.includes('ctrl')&&event.shiftKey===parts.includes('shift')&&event.altKey===parts.includes('alt')&&event.metaKey===parts.includes('meta')&&(event.key.toLowerCase()===key||event.code.toLowerCase()===physicalKey)}
export async function addToQueue(studentId:string,passType:PassType='bathroom'){return db.transaction('rw',[db.queue,db.students,db.sessions,db.settings],async()=>{if(await db.queue.where('studentId').equals(studentId).first())throw new Error('Student is already in line.');const student=await db.students.get(studentId);if(!student)throw new Error('Student was not found.');const settings=await getSettings(),sessions=await db.sessions.toArray(),date=new Date(),weekly=reconcileStudentWeeklyTime(student,sessions,settings,date),evaluated=reconcileStudentProbation(weekly,sessions,settings,date);if(evaluated!==student)await db.students.put(evaluated);const eligibility=await useEligibility(evaluated,settings,sessions,date,passType);if(!eligibility.allowed)throw new Error(eligibility.reason);const stamp=now(),item:QueueEntry={id:uid(),studentId,classId:settings.currentClassId,queuedAt:stamp,status:'waiting',passType,createdAt:stamp,updatedAt:stamp};await db.queue.add(item);return item})}
export async function startTimer(entryId:string){return db.transaction('rw',db.queue,db.queueHistory,async()=>{const q=(await db.queue.toArray()).sort((a,b)=>a.queuedAt.localeCompare(b.queuedAt));if(!q.length||q[0].id!==entryId)throw new Error('Only the first student may start the timer.');if(q.some(x=>x.status==='active'))throw new Error('A timer is already active.');const entry=q[0],stamp=now(),history:QueueHistory={id:uid(),queueEntryId:entry.id,studentId:entry.studentId,classId:entry.classId,joinedAt:entry.queuedAt,exitedAt:stamp,waitDurationSeconds:Math.max(0,Math.floor((new Date(stamp).getTime()-new Date(entry.queuedAt).getTime())/1000)),exitReason:'bathroom-started',createdAt:stamp,updatedAt:stamp};await db.queueHistory.add(history);await db.queue.update(entryId,{status:'active',startedAt:stamp,updatedAt:stamp})})}
export async function finishActive(status:Session['status']='completed'){const settings=await getSettings(),result=await db.transaction('rw',db.queue,db.students,db.sessions,async()=>{const active=await db.queue.where('status').equals('active').first();if(!active||!active.startedAt)throw new Error('No active bathroom session.');const student=await db.students.get(active.studentId),end=now(),seconds=Math.max(0,Math.floor((new Date(end).getTime()-new Date(active.startedAt).getTime())/1000)),passType=active.passType??'bathroom',warningAt=passType==='water'?90:settings.warningSeconds,overAt=passType==='water'?90:settings.overLimitSeconds,item:Session={id:uid(),studentId:active.studentId,studentName:student?.name??'Deleted student',queuedAt:active.queuedAt,startedAt:active.startedAt,endedAt:end,durationSeconds:seconds,durationFormatted:formatDuration(seconds),reachedWarning:seconds>=warningAt,overLimit:seconds>=overAt,status,passType,classId:active.classId,createdAt:end,updatedAt:end};await db.sessions.add(item);await db.queue.delete(active.id);if(student&&status==='completed'){const sessions=await db.sessions.toArray(),date=new Date(end),weekly=reconcileStudentWeeklyTime(student,sessions,settings,date),evaluated=reconcileStudentProbation(weekly,sessions,settings,date);if(evaluated!==student)await db.students.put(evaluated)}return item});await purgeDetailedHistory();return result}
export function studentStats(students:Student[],sessions:Session[],settings:Settings={...({countWaterAsBathroom:false}as Settings)}){return students.map(student=>{const completed=countedSessions(sessions,settings).filter(x=>x.studentId===student.id),recent=[...completed].sort((a,b)=>b.endedAt.localeCompare(a.endedAt))[0],over=completed.filter(x=>x.overLimit).length;return{student,total:completed.length,over,percent:completed.length?Math.round(over/completed.length*100):0,average:completed.length?Math.round(completed.reduce((a,x)=>a+x.durationSeconds,0)/completed.length):0,recent:recent?.endedAt}})}
export function parseRosterCsv(text:string,_existing:Student[]=[]){void _existing;const parsed=Papa.parse<Record<string,string>>(text,{header:true,skipEmptyLines:true}),seen=new Set<string>(),rows=(parsed.data||[]).map((r,i)=>{const name=(r.name??'').trim(),studentId=(r.studentId??'').trim();let error='';if(!name)error='Missing name';else{try{normalizeExternalId(studentId)}catch(reason){error=(reason as Error).message}}if(!error&&seen.has(studentId))error='Duplicate ID in file';seen.add(studentId);return{row:i+2,name,studentId,error,conflict:false}});if(parsed.errors.length)rows.push({row:0,name:'',studentId:'',error:'Invalid CSV',conflict:false});return rows}
const esc=(value:unknown)=>`"${String(value??'').replaceAll('"','""')}"`;
export const rosterCsv=(students:Student[])=>['name',...students.map(student=>esc(student.name))].join('\r\n');
export const historyCsv=(sessions:Session[])=>['studentName,queuedAt,startedAt,endedAt,durationSeconds,durationFormatted,reachedWarning,overLimit,status,passType,classId',...[...sessions].sort((a,b)=>b.endedAt.localeCompare(a.endedAt)).map(item=>[item.studentName,item.queuedAt,item.startedAt,item.endedAt,item.durationSeconds,item.durationFormatted,item.reachedWarning,item.overLimit,item.status,item.passType??'bathroom',item.classId??''].map(esc).join(','))].join('\r\n');
export async function purgedHistoryCsv(){await purgeDetailedHistory();return historyCsv(await db.sessions.toArray())}
export async function purgedRosterCsv(){await purgeDetailedHistory();return rosterCsv(await db.students.toArray())}
export function download(name:string,data:string,type:string){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
