import{db,defaults,getSettings,normalizedRetentionDays}from'./db';
import{deriveExternalIdHash,externalIdLast4,generateLookupSecret,normalizeExternalId,validLookupSecret}from'./privacy';
import type{LegacyStudent,Session,Settings,Student}from'./types';

let activeMigration:Promise<{migrated:boolean}>|undefined;
function validHash(value:unknown){return typeof value==='string'&&/^[0-9a-f]{64}$/.test(value)}
async function migrate(){const rawStudents=await db.students.toArray() as unknown as Array<Student|LegacyStudent>,classes=await db.classes.toArray(),enrollments=await db.enrollments.toArray(),queue=await db.queue.toArray(),queueHistory=await db.queueHistory.toArray(),rawSessions=await db.sessions.toArray() as Array<Session&{studentIdSnapshot?:string}>,bellSchedules=await db.bellSchedules.toArray(),stored=await db.settings.get('settings') as Partial<Settings>|undefined,settings={...defaults,...stored};
 const ids=new Set(rawStudents.map(student=>student.id));if(ids.size!==rawStudents.length)throw new Error('Privacy migration stopped because duplicate internal student records were found.');if(queue.some(item=>!ids.has(item.studentId))||enrollments.some(item=>!ids.has(item.studentId)))throw new Error('Privacy migration stopped because a current queue or enrollment relationship is invalid.');if(!Array.isArray(classes)||!Array.isArray(queueHistory)||!Array.isArray(bellSchedules))throw new Error('Privacy migration stopped because local data could not be validated.');
 const hasProtected=rawStudents.some(student=>validHash((student as Student).externalIdHash)),hasLegacy=rawStudents.some(student=>typeof(student as LegacyStudent).studentId==='string'),hasSnapshots=rawSessions.some(session=>'studentIdSnapshot'in session),requiresMigration=hasLegacy||hasSnapshots||settings.schemaVersion<4||settings.privacyVersion<4;if(rawStudents.some(student=>!validHash((student as Student).externalIdHash)&&typeof(student as LegacyStudent).studentId!=='string'))throw new Error('Privacy migration stopped because a student identifier is missing or invalid.');
 let secret=settings.lookupSecret;if(!validLookupSecret(secret)){if(hasProtected)throw new Error('Privacy migration stopped because protected identifiers exist without their installation lookup secret.');secret=generateLookupSecret()}
 const converted:Student[]=[];for(const raw of rawStudents){if(validHash((raw as Student).externalIdHash)){const student=raw as Student;if(!/^\d{1,4}$/.test(student.externalIdLast4))throw new Error('Privacy migration stopped because protected student metadata is invalid.');converted.push({...student})}else{const legacy=raw as LegacyStudent,normalized=normalizeExternalId(legacy.studentId),externalIdHash=await deriveExternalIdHash(secret,normalized),{studentId:_,...rest}=legacy;void _;converted.push({...rest,externalIdHash,externalIdLast4:externalIdLast4(normalized)})}}
 if(new Set(converted.map(student=>student.externalIdHash)).size!==converted.length)throw new Error('Privacy migration stopped because duplicate student IDs were detected.');
 const cleanedSessions=rawSessions.map(raw=>{const{studentIdSnapshot:_,...session}=raw;void _;return session}),now=new Date(),historyRetentionDays=normalizedRetentionDays(settings.historyRetentionDays),cutoff=now.getTime()-historyRetentionDays*86_400_000,recentSessions=cleanedSessions.filter(item=>{const time=new Date(item.endedAt).getTime();return!Number.isFinite(time)||time>=cutoff}),recentQueueHistory=queueHistory.filter(item=>{const time=new Date(item.exitedAt).getTime();return!Number.isFinite(time)||time>=cutoff}),wasConfigured=Boolean(settings.setupComplete),completedAt=settings.privacyMigrationCompletedAt??now.toISOString(),next:Settings={...settings,lookupSecret:secret,schemaVersion:4,privacyVersion:4,privacyMigrationCompletedAt:completedAt,privacyNoticeAcknowledged:requiresMigration&&wasConfigured?false:settings.privacyNoticeAcknowledged??true,historyRetentionDays,lastSuccessfulPurgeAt:now.toISOString()};
 await db.transaction('rw',[db.students,db.sessions,db.queueHistory,db.settings],async()=>{await db.students.clear();await db.students.bulkAdd(converted);await db.sessions.clear();await db.sessions.bulkAdd(recentSessions);await db.queueHistory.clear();await db.queueHistory.bulkAdd(recentQueueHistory);await db.settings.put(next)});return{migrated:requiresMigration}}
export function ensurePrivacyMigration(){if(activeMigration)return activeMigration;const run=()=>migrate();activeMigration=(typeof navigator!=='undefined'&&navigator.locks?.request?navigator.locks.request('classroom-bathroom-queue-privacy-v4',run):run()).finally(()=>{activeMigration=undefined});return activeMigration}
export async function acknowledgePrivacyNotice(){const settings=await getSettings();await db.settings.put({...settings,privacyNoticeAcknowledged:true})}
