import{useEffect,useMemo,useState}from'react';
import type{BellSchedule,ClassRecord,QueueEntry,Settings}from'./types';
import{localAppServices}from'./services';
import{dateKey}from'./schedule';

const dayNames=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
const classLabel=(item:ClassRecord)=>`${item.period||'Unknown period'} — ${item.courseTitle||'Untitled class'}`;

export default function SchedulePanel({classes,schedules,queue,settings,onChanged,onNotice}:{classes:ClassRecord[];schedules:BellSchedule[];queue:QueueEntry[];settings:Settings;onChanged:()=>Promise<void>;onNotice:(message:string)=>void}){
 const[manualClass,setManualClass]=useState(settings.currentClassId??''),[pauseAfterSwitch,setPauseAfterSwitch]=useState(false),[selectedScheduleId,setSelectedScheduleId]=useState(settings.activeScheduleId),[draft,setDraft]=useState<BellSchedule>();
 const selected=useMemo(()=>schedules.find(s=>s.id===selectedScheduleId)??schedules[0],[schedules,selectedScheduleId]);
 useEffect(()=>setDraft(selected?structuredClone(selected):undefined),[selected]);
 const paused=settings.autoSchedulePausedDate===dateKey(new Date());
 async function switchClass(){if(queue.some(q=>q.status==='waiting')&&!confirm('Switching classes will remove every waiting student from the outgoing class. Continue?'))return;await localAppServices.manualSwitch(manualClass||undefined,pauseAfterSwitch);await onChanged();onNotice('Class switched. Active bathroom timers were preserved.')}
 async function saveSchedule(){if(!draft)return;for(const blocks of Object.values(draft.days))for(const block of blocks)if(block.start>=block.end)return onNotice(`${block.label} must end after it starts.`);await localAppServices.saveSchedule(draft);await onChanged();onNotice('Bell schedule saved.')}
 async function restore(){if(!confirm('Replace the customized default schedule with the built-in school bell schedule?'))return;await localAppServices.restoreDefaultSchedule();await onChanged();onNotice('Default bell schedule restored.')}
 async function chooseToday(value:string){await localAppServices.chooseTodaySchedule(value||undefined);await onChanged();onNotice(value?'Today’s schedule selected.':'Today’s schedule override cleared.')}
 function changeBlock(day:number,id:string,changes:Record<string,string|undefined>){if(!draft)return;setDraft({...draft,days:{...draft.days,[day]:draft.days[day].map(block=>block.id===id?{...block,...changes}:block)}})}
 return <>
  <section className="card usage-settings"><h1>Switch Class / Period</h1>{paused&&<p className="banner"><b>Automatic scheduling is paused for today.</b></p>}<label>Available Class<select value={manualClass} onChange={e=>setManualClass(e.target.value)}><option value="">No active class</option>{classes.map(c=><option key={c.id} value={c.id}>{classLabel(c)}</option>)}</select></label><label className="check-label"><input type="checkbox" checked={pauseAfterSwitch} onChange={e=>setPauseAfterSwitch(e.target.checked)}/> Pause automatic scheduling for the rest of today</label><p>{pauseAfterSwitch?'The manual class will remain selected until tomorrow.':'Automatic scheduling resumes at the next scheduled transition.'}</p><button className="primary" onClick={switchClass}>Switch Class / Period</button><div className="actions">{paused?<button onClick={async()=>{await localAppServices.resumeAutomatic();await onChanged();onNotice('Automatic schedule resumed.')}}>Resume automatic schedule</button>:<button onClick={async()=>{await localAppServices.pauseAutomatic();await onChanged();onNotice('Automatic schedule paused for today.')}}>Pause automatic schedule for today</button>}</div></section>
  <section className="card bell-schedule"><div className="titleline"><div><h1>Bell Schedule</h1><p>Default School Bell Schedule</p></div><button className="danger" onClick={restore}>Restore default bell schedule</button></div><label>Today’s Schedule<select value={settings.todayScheduleDate===dateKey(new Date())?settings.todayScheduleId??'':''} onChange={e=>chooseToday(e.target.value)}><option value="">Use normal schedule</option>{schedules.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Schedule to edit<select value={selectedScheduleId} onChange={e=>setSelectedScheduleId(e.target.value)}>{schedules.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>{draft&&[1,2,3,4,5].map(day=><div className="schedule-day" key={day}><h2>{dayNames[day]}</h2>{draft.days[day].map(item=><div className="schedule-row" key={item.id}><b>{item.label}</b><label>Start<input aria-label={`${dayNames[day]} ${item.label} start`} type="time" value={item.start} onChange={e=>changeBlock(day,item.id,{start:e.target.value})}/></label><label>End<input aria-label={`${dayNames[day]} ${item.label} end`} type="time" value={item.end} onChange={e=>changeBlock(day,item.id,{end:e.target.value})}/></label>{(item.kind==='class'||item.kind==='pcbl')&&<label>Class mapping<select aria-label={`${dayNames[day]} ${item.label} class mapping`} value={item.classId??''} onChange={e=>changeBlock(day,item.id,{classId:e.target.value||undefined})}><option value="">No class mapped</option>{classes.map(c=><option key={c.id} value={c.id}>{classLabel(c)}</option>)}</select></label>}</div>)}</div>)}<button className="primary" onClick={saveSchedule}>Save bell schedule</button></section>
 </>
}
