import{db,defaults,atomicReplace,snapshot}from'./db';import{repositories}from'./repositories';import{uid,now}from'./lib';import type{Student,Settings,ClassRecord,Enrollment}from'./types';import type{AeriesParseResult}from'./aeries';import{displayAeriesName}from'./aeries';
export const localAppServices={snapshot,replaceAll:atomicReplace,
 async queueCount(){return(await repositories.queue.list()).length},async queueForStudent(id:string){return repositories.queue.findByStudent(id)},async removeQueue(id:string){return repositories.queue.delete(id)},
 async reorderQueue(entries:{id:string}[]){const base=Date.now();await db.transaction('rw',db.queue,async()=>{for(let i=0;i<entries.length;i++)await repositories.queue.update(entries[i].id,{queuedAt:new Date(base+i).toISOString(),updatedAt:now()})})},async clearWaiting(){await db.queue.where('status').equals('waiting').delete()},
 async saveSettings(settings:Settings){return repositories.settings.put(settings)},async clearHistory(){return repositories.sessions.clear()},async resetAll(){return atomicReplace({students:[],classes:[],enrollments:[],queue:[],sessions:[],settings:defaults})},
 async addStudent(student:Student){return repositories.students.add(student)},async updateStudent(id:string,changes:Partial<Student>){return repositories.students.update(id,{...changes,updatedAt:now()})},async deleteStudent(id:string){return repositories.students.delete(id)},
 async importStandard(rows:{name:string;studentId:string}[],update:boolean){for(const row of rows){const old=await repositories.students.findByExternalId(row.studentId);if(old){if(update)await repositories.students.update(old.id,{name:row.name,updatedAt:now()})}else{const t=now();await repositories.students.add({id:uid(),name:row.name,studentId:row.studentId,createdAt:t,updatedAt:t,maxUses:null,banned:false})}}},
 async importAeries(preview:AeriesParseResult,selected:Set<string>,replace:Set<string>,format:'aeries'|'first-last'){await db.transaction('rw',db.students,db.classes,db.enrollments,async()=>{const classIds=new Map<string,string>();for(const c of preview.classes){const id=uid(),t=now();const record:ClassRecord={id,createdAt:t,updatedAt:t,period:c.period,courseTitle:c.courseTitle,sectionNumber:c.sectionNumber,courseId:c.courseId,teacherName:c.teacher,calendar:c.calendar,room:c.room,schoolYear:c.schoolYear};await repositories.classes.add(record);classIds.set(c.key,id)}for(const s of preview.students){if(!selected.has(s.studentId)||s.conflictingNames.length)continue;const name=displayAeriesName(s.rawName,format);let student=await repositories.students.findByExternalId(s.studentId);if(student){if(student.name!==name&&replace.has(s.studentId)){await repositories.students.update(student.id,{name,updatedAt:now()});student={...student,name}}}else{const t=now();student={id:uid(),name,studentId:s.studentId,createdAt:t,updatedAt:t,maxUses:null,banned:false};await repositories.students.add(student)}for(const key of s.classKeys){const classId=classIds.get(key);if(!classId)continue;const exists=await db.enrollments.where('[studentId+classId]').equals([student.id,classId]).first();if(!exists){const t=now(),enrollment:Enrollment={id:uid(),studentId:student.id,classId,createdAt:t,updatedAt:t};await repositories.enrollments.add(enrollment)}}}})},
 repositories
};
