import{db,defaults,atomicReplace,snapshot,getSettings,ensureDefaultSchedule,normalizeSettings}from'./db';
import{repositories}from'./repositories';
import type{Student,Settings,ClassRecord,Enrollment,QueueEntry,QueueExitReason,QueueHistory,BellSchedule,ScheduleState,ProbationPolicy,WeeklyTimePolicy,UsageLimitMode}from'./types';
import type{AeriesParseResult}from'./aeries';
import{displayAeriesName}from'./aeries';
import{applySuggestedMappings,builtInDefaultSchedule,dateKey,DEFAULT_SCHEDULE_ID,resolveSchedule}from'./schedule';
import{deriveExternalIdHash,externalIdLast4,normalizeExternalId}from'./privacy';
import{assessProbation,normalizeProbationPolicy,reconcileStudentProbation,validateProbationPolicy}from'./probation';
import{assessWeeklyTime,normalizeWeeklyTimePolicy,reconcileStudentWeeklyTime,validateWeeklyTimePolicy}from'./weeklyTime';

const uid=()=>crypto.randomUUID(),now=()=>new Date().toISOString();
const stateId=(state:ScheduleState)=>`${state.dateKey}:${state.block?.id??'non-class'}`;
function historyFor(entry:QueueEntry,reason:QueueExitReason,exitedAt=now()):QueueHistory{return{id:uid(),queueEntryId:entry.id,studentId:entry.studentId,classId:entry.classId,joinedAt:entry.queuedAt,exitedAt,waitDurationSeconds:Math.max(0,Math.floor((new Date(exitedAt).getTime()-new Date(entry.queuedAt).getTime())/1000)),exitReason:reason,createdAt:exitedAt,updatedAt:exitedAt}}
async function selectedSchedule(settings:Settings,date:Date){await ensureDefaultSchedule();const today=dateKey(date),id=settings.todayScheduleDate===today&&settings.todayScheduleId?settings.todayScheduleId:settings.activeScheduleId;return(await repositories.bellSchedules.get(id))??(await repositories.bellSchedules.get(DEFAULT_SCHEDULE_ID))??builtInDefaultSchedule(date)}
function withProbationLock<T>(run:()=>Promise<T>){return typeof navigator!=='undefined'&&navigator.locks?.request?navigator.locks.request('classroom-bathroom-queue-probation',run):run()}
function reconcileStudentRestrictions(student:Student,sessions:import('./types').Session[],settings:Settings,date:Date,forceWeekly=false,forceProbation=false){const weekly=reconcileStudentWeeklyTime(student,sessions,settings,date,forceWeekly);return reconcileStudentProbation(weekly,sessions,settings,date,forceProbation)}
function reconcileSettingsChange(student:Student,sessions:import('./types').Session[],current:Settings,next:Settings,date:Date){const oldWeekly=assessWeeklyTime(student,sessions,current,date).automaticSuspensionTriggered,newWeekly=assessWeeklyTime(student,sessions,next,date).automaticSuspensionTriggered,oldProbation=assessProbation(student,sessions,current,date).suspensionTriggered,newProbation=assessProbation(student,sessions,next,date).suspensionTriggered;let evaluated=student;if(!(oldWeekly&&newWeekly))evaluated=reconcileStudentWeeklyTime(evaluated,sessions,next,date,!oldWeekly&&newWeekly);if(!(oldProbation&&newProbation))evaluated=reconcileStudentProbation(evaluated,sessions,next,date,!oldProbation&&newProbation);return evaluated}
async function reconcileProbationRecords(date=new Date()){return withProbationLock(()=>db.transaction('rw',[db.students,db.sessions,db.settings],async()=>{const settings=await getSettings(),sessions=await db.sessions.toArray(),students=await db.students.toArray();for(const student of students){const next=reconcileStudentRestrictions(student,sessions,settings,date);if(next!==student)await db.students.put(next)}}))}
async function updateSettingsWithEvaluation(update:(current:Settings)=>Settings){return withProbationLock(()=>db.transaction('rw',[db.students,db.sessions,db.settings],async()=>{const current=await getSettings(),next=normalizeSettings(update(current)),date=new Date(),sessions=await db.sessions.toArray(),students=await db.students.toArray();await repositories.settings.put(next);for(const student of students){const evaluated=reconcileSettingsChange(student,sessions,current,next,date);if(evaluated!==student)await db.students.put(evaluated)}return next}))}
async function saveSettingsWithEvaluation(input:Settings){return updateSettingsWithEvaluation(()=>input)}

export const localAppServices={snapshot,replaceAll:atomicReplace,repositories,
 async externalHash(rawId:string){const settings=await getSettings();return deriveExternalIdHash(settings.lookupSecret,rawId)},
 async findStudentByExternalId(rawId:string){const settings=await getSettings(),hash=await deriveExternalIdHash(settings.lookupSecret,rawId);return repositories.students.findByExternalHash(hash)},
 async queueCount(){return(await repositories.queue.list()).length},async queueForStudent(id:string){return repositories.queue.findByStudent(id)},
 async removeQueue(id:string,reason:QueueExitReason='teacher-removed'){const entry=await repositories.queue.get(id);if(!entry)return;if(entry.status==='waiting')await repositories.queueHistory.add(historyFor(entry,reason));await repositories.queue.delete(id)},
 async reorderQueue(entries:{id:string}[]){const base=Date.now();await db.transaction('rw',db.queue,async()=>{for(let i=0;i<entries.length;i++)await repositories.queue.update(entries[i].id,{queuedAt:new Date(base+i).toISOString(),updatedAt:now()})})},
 async clearWaiting(reason:QueueExitReason='teacher-removed',classId?:string){return db.transaction('rw',db.queue,db.queueHistory,async()=>{const waiting=(await db.queue.where('status').equals('waiting').toArray()).filter(q=>!classId||q.classId===classId),exited=now();for(const entry of waiting){await db.queueHistory.add(historyFor(entry,reason,exited));await db.queue.delete(entry.id)}return waiting})},
 async quickClear(){return this.clearWaiting('teacher-quick-clear')},
 async undoQuickClear(entries:QueueEntry[]){await db.transaction('rw',db.queue,db.queueHistory,async()=>{for(const entry of entries){const record=await db.queueHistory.where('queueEntryId').equals(entry.id).and(x=>x.exitReason==='teacher-quick-clear').first();if(record)await db.queueHistory.delete(record.id);if(!await db.queue.get(entry.id))await db.queue.put(entry)}})},
 async saveSettings(settings:Settings){return saveSettingsWithEvaluation(settings)},async clearHistory(){return repositories.sessions.clear()},async resetAll(){return atomicReplace({students:[],classes:[],enrollments:[],queue:[],queueHistory:[],sessions:[],bellSchedules:[builtInDefaultSchedule()],settings:defaults})},
 async saveUsageLimitMode(mode:UsageLimitMode){if(mode!=='bathroom-passes'&&mode!=='weekly-time')throw new Error('Select a valid usage-limit mode.');return updateSettingsWithEvaluation(current=>({...current,usageLimitMode:mode,weeklyTimePolicy:mode==='weekly-time'?{...current.weeklyTimePolicy,enabled:true}:current.weeklyTimePolicy}))},
 async reconcileProbation(date=new Date()){return reconcileProbationRecords(date)},
 async saveProbationPolicy(input:ProbationPolicy){const normalized=normalizeProbationPolicy(input),validation=validateProbationPolicy(normalized);if(validation)throw new Error(validation);return updateSettingsWithEvaluation(current=>{const before={...current.probationPolicy,updatedAt:undefined},after={...normalized,updatedAt:undefined},changed=JSON.stringify(before)!==JSON.stringify(after),updatedAt=changed?now():current.probationPolicy.updatedAt;return{...current,probationPolicy:{...normalized,updatedAt}}})},
 async saveWeeklyTimePolicy(input:WeeklyTimePolicy,acknowledged:boolean){const normalized=normalizeWeeklyTimePolicy(input);return updateSettingsWithEvaluation(current=>{const hasAcknowledgement=current.probationPolicy.automaticSuspensionAcknowledged||acknowledged,validation=validateWeeklyTimePolicy(normalized,hasAcknowledgement);if(validation)throw new Error(validation);const before={...current.weeklyTimePolicy,updatedAt:undefined},after={...normalized,updatedAt:undefined},changed=JSON.stringify(before)!==JSON.stringify(after),updatedAt=changed?now():current.weeklyTimePolicy.updatedAt;return{...current,probationPolicy:{...current.probationPolicy,automaticSuspensionAcknowledged:hasAcknowledgement},weeklyTimePolicy:{...normalized,updatedAt}}})},
 async setProbationExempt(id:string,exempt:boolean){const student=await repositories.students.get(id);if(!student)return;const changes:Partial<Student>={probationExempt:exempt,updatedAt:now()};if(exempt&&student.passSuspension?.kind==='automatic'&&student.passSuspension.source!=='weekly-time')changes.passSuspension=undefined;await repositories.students.update(id,changes)},
 async endPassSuspension(id:string){await repositories.students.update(id,{passSuspension:undefined,updatedAt:now()})},
 async applyManualSuspension(id:string,days:number){const stamp=now();await repositories.students.update(id,{banned:false,passSuspension:{kind:'manual',source:'manual',startedAt:stamp,endsAt:new Date(new Date(stamp).getTime()+days*86_400_000).toISOString(),reasons:['Teacher-applied temporary suspension']},updatedAt:stamp})},
 async adjustPassSuspension(id:string,days:number){const student=await repositories.students.get(id);if(!student?.passSuspension)return;const stamp=now();await repositories.students.update(id,{passSuspension:{...student.passSuspension,endsAt:new Date(new Date(stamp).getTime()+days*86_400_000).toISOString()},updatedAt:stamp})},
 async rearmProbation(id:string){const stamp=now();await db.transaction('rw',[db.students,db.sessions,db.settings],async()=>{const student=await db.students.get(id);if(!student)return;const settings=await getSettings(),sessions=await db.sessions.toArray(),rearmed={...student,lastAutoSuspensionTriggerKey:undefined,lastWeeklyTimeSuspensionTriggerKey:undefined,updatedAt:stamp},evaluated=reconcileStudentRestrictions(rearmed,sessions,settings,new Date(stamp),true,true);await db.students.put(evaluated)})},
 async addStudent(student:Omit<Student,'externalIdHash'|'externalIdLast4'>&{studentId:string}){const normalized=normalizeExternalId(student.studentId),settings=await getSettings(),externalIdHash=await deriveExternalIdHash(settings.lookupSecret,normalized),{studentId:_,...rest}=student;void _;if(await repositories.students.findByExternalHash(externalIdHash))throw new Error('Student ID must be unique.');return repositories.students.add({...rest,externalIdHash,externalIdLast4:externalIdLast4(normalized)})},async replaceStudentId(id:string,rawId:string){const normalized=normalizeExternalId(rawId),settings=await getSettings(),externalIdHash=await deriveExternalIdHash(settings.lookupSecret,normalized),existing=await repositories.students.findByExternalHash(externalIdHash);if(existing&&existing.id!==id)throw new Error('Student ID must be unique.');return repositories.students.update(id,{externalIdHash,externalIdLast4:externalIdLast4(normalized),updatedAt:now()})},async updateStudent(id:string,changes:Partial<Student>){return withProbationLock(()=>db.transaction('rw',[db.students,db.sessions,db.settings],async()=>{const current=await db.students.get(id);if(!current)return 0;const settings=await getSettings(),sessions=await db.sessions.toArray(),date=new Date(),updated={...current,...changes,updatedAt:now()},wasWeekly=assessWeeklyTime(current,sessions,settings,date).automaticSuspensionTriggered,isWeekly=assessWeeklyTime(updated,sessions,settings,date).automaticSuspensionTriggered;let evaluated=updated;if(!(wasWeekly&&isWeekly))evaluated=reconcileStudentWeeklyTime(evaluated,sessions,settings,date,!wasWeekly&&isWeekly);evaluated=reconcileStudentProbation(evaluated,sessions,settings,date);await db.students.put(evaluated);return 1}))},async deleteStudent(id:string){return repositories.students.delete(id)},
 async scheduleState(date=new Date()){const settings=await getSettings(),schedule=await selectedSchedule(settings,date),resolved=resolveSchedule(schedule,date);if(settings.autoSchedulePausedDate===dateKey(date)){const current=settings.currentClassId;return{...resolved,kind:current?'class':'non-class',label:current?'Manual class':'Non-class',classId:current,lineOpen:true} as ScheduleState}if(settings.manualOverrideBlockId&&settings.manualOverrideBlockId===(resolved.block?.id??'non-class')){const current=settings.currentClassId;return{...resolved,kind:current?'class':'non-class',label:current?'Manual class':'Non-class',classId:current,lineOpen:true} as ScheduleState}return resolved},
 async reconcileSchedule(date=new Date()){const settings=await getSettings(),today=dateKey(date),schedule=await selectedSchedule(settings,date),resolved=resolveSchedule(schedule,date),resolvedId=stateId(resolved),lastTime=settings.lastScheduleStateId?.split('|')[1],lastId=settings.lastScheduleStateId?.split('|')[0],clockBack=lastTime&&new Date(lastTime).getTime()>date.getTime()+300000;let next={...settings,clockWarning:clockBack?'The Chromebook clock moved backward. Verify the time before relying on duration statistics.':undefined};if(next.autoSchedulePausedDate&&next.autoSchedulePausedDate!==today)next={...next,autoSchedulePausedDate:undefined};if(next.todayScheduleDate&&next.todayScheduleDate!==today)next={...next,todayScheduleDate:undefined,todayScheduleId:undefined};const paused=next.autoSchedulePausedDate===today,holding=Boolean(next.manualOverrideBlockId&&next.manualOverrideBlockId===(resolved.block?.id??'non-class'));if(next.manualOverrideBlockId&&!holding)next={...next,manualOverrideBlockId:undefined};if(!paused&&!holding){const changed=Boolean(lastId&&lastId!==resolvedId)||next.currentClassId!==resolved.classId;if(changed)await this.clearWaiting('period-ended');next={...next,currentClassId:resolved.lineOpen?resolved.classId:undefined}}next={...next,lastScheduleStateId:`${resolvedId}|${date.toISOString()}`};await repositories.settings.put(next);return this.scheduleState(date)},
 async manualSwitch(classId:string|undefined,pauseForToday:boolean,date=new Date()){const current=await this.scheduleState(date),settings=await getSettings();await this.clearWaiting('manual-class-switch');await repositories.settings.put({...settings,currentClassId:classId,autoSchedulePausedDate:pauseForToday?dateKey(date):undefined,manualOverrideBlockId:pauseForToday?undefined:(current.block?.id??'non-class')});return this.scheduleState(date)},
 async pauseAutomatic(date=new Date()){const settings=await getSettings();await repositories.settings.put({...settings,autoSchedulePausedDate:dateKey(date),manualOverrideBlockId:undefined})},
 async resumeAutomatic(date=new Date()){const settings=await getSettings();await repositories.settings.put({...settings,autoSchedulePausedDate:undefined,manualOverrideBlockId:undefined,lastScheduleStateId:undefined});return this.reconcileSchedule(date)},
 async chooseTodaySchedule(scheduleId:string|undefined,date=new Date()){const settings=await getSettings();await repositories.settings.put({...settings,todayScheduleId:scheduleId,todayScheduleDate:scheduleId?dateKey(date):undefined,lastScheduleStateId:undefined});return this.reconcileSchedule(date)},
 async saveSchedule(schedule:BellSchedule){await repositories.bellSchedules.put({...schedule,builtIn:false,updatedAt:now()})},
 async restoreDefaultSchedule(){const fresh=builtInDefaultSchedule();const classes=await repositories.classes.list();await repositories.bellSchedules.put(applySuggestedMappings(fresh,classes));const settings=await getSettings();await repositories.settings.put({...settings,activeScheduleId:DEFAULT_SCHEDULE_ID,lastScheduleStateId:undefined})},
 async importStandard(rows:{name:string;studentId:string}[],update:boolean){const settings=await getSettings();for(const row of rows){const normalized=normalizeExternalId(row.studentId),externalIdHash=await deriveExternalIdHash(settings.lookupSecret,normalized),old=await repositories.students.findByExternalHash(externalIdHash);if(old){if(update)await repositories.students.update(old.id,{name:row.name,updatedAt:now()})}else{const t=now();await repositories.students.add({id:uid(),name:row.name,externalIdHash,externalIdLast4:externalIdLast4(normalized),createdAt:t,updatedAt:t,maxUses:null,banned:false})}}},
 async importAeries(preview:AeriesParseResult,selected:Set<string>,replace:Set<string>,format:'aeries'|'first-last'){const settings=await getSettings(),prepared=new Map<string,{hash:string;last4:string}>();for(const student of preview.students){if(selected.has(student.studentId)){const normalized=normalizeExternalId(student.studentId);prepared.set(student.studentId,{hash:await deriveExternalIdHash(settings.lookupSecret,normalized),last4:externalIdLast4(normalized)})}}await db.transaction('rw',db.students,db.classes,db.enrollments,db.bellSchedules,async()=>{const classIds=new Map<string,string>();for(const c of preview.classes){const id=uid(),t=now(),record:ClassRecord={id,createdAt:t,updatedAt:t,period:c.period,courseTitle:c.courseTitle,sectionNumber:c.sectionNumber,courseId:c.courseId,teacherName:c.teacher,calendar:c.calendar,room:c.room,schoolYear:c.schoolYear};await repositories.classes.add(record);classIds.set(c.key,id)}for(const s of preview.students){if(!selected.has(s.studentId)||s.conflictingNames.length)continue;const protectedId=prepared.get(s.studentId)!;const name=displayAeriesName(s.rawName,format);let student=await repositories.students.findByExternalHash(protectedId.hash);if(student){if(student.name!==name&&replace.has(s.studentId)){await repositories.students.update(student.id,{name,updatedAt:now()});student={...student,name}}}else{const t=now();student={id:uid(),name,externalIdHash:protectedId.hash,externalIdLast4:protectedId.last4,createdAt:t,updatedAt:t,maxUses:null,banned:false};await repositories.students.add(student)}for(const key of s.classKeys){const classId=classIds.get(key);if(!classId)continue;const exists=await db.enrollments.where('[studentId+classId]').equals([student.id,classId]).first();if(!exists){const t=now(),enrollment:Enrollment={id:uid(),studentId:student.id,classId,createdAt:t,updatedAt:t};await repositories.enrollments.add(enrollment)}}}await ensureDefaultSchedule();const classes=await repositories.classes.list();for(const schedule of await repositories.bellSchedules.list())await repositories.bellSchedules.put(applySuggestedMappings(schedule,classes))})}
};
