import{useRef,useState}from'react';
import type{Backup,Settings,Student}from'./types';
import{defaults}from'./db';
import{localAppServices}from'./services';
import{makePin,now,parseRosterCsv,uid,validateBackup,validateStudent}from'./lib';
import AeriesImportPanel from'./AeriesImportPanel';

export default function SetupFlow({students,onChanged,onDone}:{students:Student[];onChanged:()=>Promise<void>;onDone:()=>Promise<void>}){
 const[step,setStep]=useState<'pin'|'roster'>('pin'),[pin,setPin]=useState(''),[confirmPin,setConfirmPin]=useState(''),[pinSettings,setPinSettings]=useState<Settings>(),[error,setError]=useState(''),[notice,setNotice]=useState(''),[manual,setManual]=useState(false),[name,setName]=useState(''),[studentId,setStudentId]=useState(''),[backup,setBackup]=useState<Backup>(),standard=useRef<HTMLInputElement>(null),restore=useRef<HTMLInputElement>(null);
 async function continueFromPin(){if(pin.length<4)return setError('Choose a PIN with at least four digits.');if(!/^\d+$/.test(pin))return setError('PIN must contain digits only.');if(pin!==confirmPin)return setError('PINs do not match.');const settings={...defaults,...await makePin(pin),setupComplete:false};await localAppServices.saveSettings(settings);setPinSettings(settings);setError('');setStep('roster')}
 async function finish(){if(!pinSettings)return;await localAppServices.saveSettings({...pinSettings,setupComplete:true});await onDone()}
 async function addStudent(){const validation=validateStudent(name,studentId,students);if(validation)return setError(validation);const stamp=now();await localAppServices.addStudent({id:uid(),name:name.trim(),studentId:studentId.trim(),createdAt:stamp,updatedAt:stamp,maxUses:null,banned:false});setName('');setStudentId('');setError('');await onChanged();setNotice('Student added.')}
 async function importStandard(file?:File){if(!file)return;const rows=parseRosterCsv(await file.text(),students);if(rows.some(row=>row.error))return setError('The standard roster has errors. Correct the file and try again.');await localAppServices.importStandard(rows,false);await onChanged();setError('');setNotice('Standard roster imported.')}
 async function chooseBackup(file?:File){if(!file)return;try{const parsed=JSON.parse(await file.text());if(!validateBackup(parsed))throw new Error('Invalid or unsupported backup file.');setBackup(parsed);setError('')}catch(e){setBackup(undefined);setError((e as Error).message)}}
 async function applyBackup(){if(!backup||!pinSettings)return;await localAppServices.replaceAll({students:backup.students,classes:backup.classes??[],enrollments:backup.enrollments??[],queue:backup.queue,queueHistory:backup.queueHistory??[],sessions:backup.sessions,bellSchedules:backup.bellSchedules??[],settings:{...defaults,...backup.settings,pinHash:pinSettings.pinHash,pinSalt:pinSettings.pinSalt,setupComplete:true} as Settings});await onDone()}
 if(step==='pin')return <main className="setup setup-simple"><p className="eyebrow">First-time setup</p><h1>Create your teacher PIN</h1><p>The PIN protects teacher settings on this device. It is not a teacher account.</p><section className="card setup-card"><label>Teacher PIN<input value={pin} onChange={e=>setPin(e.target.value)} inputMode="numeric" type="password"/></label><label>Confirm PIN<input value={confirmPin} onChange={e=>setConfirmPin(e.target.value)} inputMode="numeric" type="password"/></label>{error&&<p className="error" role="alert">{error}</p>}<button className="primary hero" onClick={continueFromPin}>Continue</button></section></main>;
 return <main className="setup setup-simple"><p className="eyebrow">Optional roster setup</p><h1>Set up your roster</h1><p>You can import students now, restore a previous backup, add students manually, or do this later.</p><p aria-live="polite"><b>{students.length} student{students.length===1?'':'s'} currently added</b></p>{notice&&<p className="privacy" role="status">{notice}</p>}<div className="setup-options"><AeriesImportPanel students={students} onChanged={onChanged} onNotice={setNotice}/><section className="card"><h2>Restore an installation</h2><button className="primary hero" onClick={()=>restore.current?.click()}>Restore Full Backup</button><input hidden ref={restore} type="file" accept="application/json,.json" onChange={e=>chooseBackup(e.target.files?.[0])}/>{backup&&<div className="privacy"><b>Valid full backup ready</b><p>{backup.students.length} students, {backup.sessions.length} bathroom sessions, and complete app settings.</p><button className="primary" onClick={applyBackup}>Confirm Restore Full Backup</button></div>}</section><section className="card"><h2>Other roster options</h2><button onClick={()=>standard.current?.click()}>Import Standard Roster</button><input hidden ref={standard} type="file" accept=".csv,text/csv" onChange={e=>importStandard(e.target.files?.[0])}/><button onClick={()=>setManual(value=>!value)}>Add Student Manually</button>{manual&&<div><label>Full name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Student ID<input value={studentId} inputMode="numeric" onChange={e=>setStudentId(e.target.value)}/></label><button onClick={addStudent}>Add Student</button></div>}</section></div>{error&&<p className="error" role="alert">{error}</p>}<button className="primary hero continue-empty" onClick={finish}>{students.length?'Continue to App':'Continue Without Students'}</button></main>
}
